### ISSUE TITLE
1.19.2: Unknown custom packed identifier: plugin:chcred

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2156] opened 2022-10-10 04:34 UTC
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Error log (if applicable)

https://gist.github.com/BearLeonLight/c7272e5ca00528f34ee4076ab6dd1832

### "/chc debug" output (strongly recommended)

#2153

### Information about the issue/bug

When I'm using Velocity, players who use CHC will keep getting this message.
If you need me to provide those settings files I can provide them.

**Comment by ElBananaa** [comment] 2022-10-10 11:11
This is a dupe of 2 different issues.
The unknown custom packed identifier is currently being fixed (the latest chc/bungeecontrol should've fixed it for bungeecord but appears to be broken. As for velocity, we're waiting for the maintainer of velocitycontrol to make the changes.

**Closed as completed by ElBananaa** 2022-10-10 11:11 UTC
Labels: velocity
