### ISSUE TITLE
1.19.2: users no longer need permissions to use colors/formatting codes?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl#2162] opened 2022-10-18 20:40 UTC
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

https://ufile.io/n5ttx5w9

### Information about the issue/bug

Players can once again use codes for underline, strikethrough and obfuscate even though I have permissions to these formats set intentionally to false for all ranks.  Seems that the permissions are no longer being obeyed, this appears to carry over into all other color codes (I see occassional use of ultra-dark colors I have also disabled via permissions).

**Comment by ElBananaa** [comment] 2022-10-18 23:35
I am completely unable to reproduce your issue, whether it's with color codes or decoration codes.
Please update the plugin to the latest version available and try again.

I'm closing this issue, but let me know here if you still need help.

**Closed as completed by ElBananaa** 2022-10-18 23:35 UTC

**Comment by mrcoffee1026** [comment] 2022-10-19 12:47
Grabbed latest 10.14.4: permissions to obfuscation, underline, bold, several dark colors are explicitely set to false yet all of them can be used by any user regardless of permissions???
Example "chatcontrol.color.black" "chatcontrol.color.obfuscated" <- these are what are suggested when setting permissions, have you changed them again?

**Comment by ElBananaa** [comment] 2022-10-19 13:07
> Grabbed latest 10.14.4: permissions to obfuscation, underline, bold, several dark colors are explicitely set to false yet all of them can be used by any user regardless of permissions??? Example "chatcontrol.color.black" "chatcontrol.color.obfuscated" <- these are what are suggested when setting permissions, have you changed them again?

No these permissions didn't change, and once again, as I said, I am unable to reproduce, they work fine for me. @kangarko

**Comment by mrcoffee1026** [comment] 2022-10-19 23:25
it's essentialsx overriding chat somehow (even though we're not allowing their chat addon nor their color permissions), my bet is on this recent change as what's ruining permissions:
https://github.com/EssentialsX/Essentials/pull/5076

**Comment by ElBananaa** [comment] 2022-10-20 00:28
Alright, so I just ran deeper tests with Essentials `2.20.0-dev+13-f91dfed` (latest dev build as of today), and I still am unable to reproduce your issue.
My guess is that this most likely comes from a setup issue on your side, or another plugin conflicting with chatcontrol.
So I suggest you try to reproduce the issue on a completely fresh test server with only chatcontrol and its dependencies installed, if you can't reproduce, then try to use your chatcontrol config from your prod server, and if it still doesn't happen, then start adding plugins back to your test server until you find the one that may be causing this.

**Comment by mrcoffee1026** [comment] 2022-10-20 20:53
further checking into essentials builds even much further back than that didn't resolve the issue... further investigation shows that it is necessary to have both essentialsX and PlaceholderAPI installed: ONLY those two plugins will result in all permisison bypass access to virtrually every color, not a chatcontrol thing.  Turns out that I was 0.0.1 versions behind :(
