### ISSUE TITLE
1.17.1: Do you have Discord support?

### ISSUE THREAD

**Issue by iKhomy** [kangarko/ChatControl#1204] opened 2021-08-05 13:03 UTC
Hello,

Do you have a Discord server where you can offer some support?

EDIT: I just bought it, but I'm running Purpur because of its optimisations. do you think I should switch to Paper? I say this because Paper takes up three times as many resources as Purpur.

**Comment by ElBananaa** [comment] 2021-08-05 16:01
Hey!
Yes, we do have a discord that you can join using this link : https://mineacademy.org/discord
We also provide support in a private channel. If you'd like to be added to the channel, we would need your discord full name#id
However, this is the best place to get a propper and fast help.

Regarding your server software, you can absolutely use Purpur. The message is simply a warning, but, from my own experience, I've never encountered an issue caused by purpur with the plugin in 9 months.

**Comment by iKhomy** [comment] 2021-08-05 16:11
Hola,

Thank you, I have been able to join your discord.

**Comment by ElBananaa** [comment] 2021-08-05 16:15
> iKhomy#9451

Great thanks!
I sent a message to Kangarko so he can add you to the channel. This should hopefully be done within this week of the next week.

May I close this issue?
(Also, could we please stick to english? My spanish is a bit rusted, so I can understand a few things, but not much unfortunately)

**Closed as completed** 2021-08-05 16:21 UTC
