### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#2163] opened 2022-10-18 21:33 UTC
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

Paper: https://gist.github.com/MithrandirCraft/6590414c9ae76d886fff02fd8c601c79
Waterfall: https://gist.github.com/MithrandirCraft/dc3092591dfa5643413f0884bf0f45e5

### "/chc debug" output (strongly recommended)

sent via email

### Information about the issue/bug

Just errors on console.

**Comment by ElBananaa** [comment] 2022-10-18 23:09
Dupe of #2151. Update the plugin.

**Closed as completed by ElBananaa** 2022-10-18 23:09 UTC
