### ISSUE TITLE
1.19.2: Velocity link not working on latest version

### ISSUE THREAD

**Issue by DJIronic** [kangarko/ChatControl#2190] opened 2022-11-20 09:21 UTC
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Information about the issue/bug

With the latest version of the plugin, Velocity sync does not work. We downgraded so the functionality works now, but on the latest version purchased on builtbybit is not working with the latest velocity.

I think my issue is nearly a duplicate of https://github.com/kangarko/ChatControl-Red/issues/2187, but on a 1.19.2 version.

**Comment by ElBananaa** [comment] 2022-11-20 20:22
Dupe of #2187. Let's continue there

**Closed as completed by ElBananaa** 2022-11-20 20:22 UTC
Labels: velocity
