### ISSUE TITLE
1.12.2: Cannot use commands after tour confirm

### ISSUE THREAD

**Issue by mfcc168** [kangarko/ChatControl#1975] opened 2022-07-08 13:20 UTC
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9072318/debug.zip)
![image](https://user-images.githubusercontent.com/88373848/177999919-6c3902ba-1a9f-4913-9ba3-594ae9f95ed7.png)

Minecraft Version: 1.12.2
MySQL: false
BungeeCord: true

**Comment by ElBananaa** [comment] 2022-07-08 14:58
Dupe of #1974.
I already told you there what to do. There's no need to open a new issue, if you have questions to ask, do it in #1974.

**Closed as completed by ElBananaa** 2022-07-08 14:58 UTC
