### ISSUE TITLE
1.18.2 File line endings are being changed based on what platform you run a server on.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2328] opened 2023-04-05 11:08 UTC
### "/version ChatControlRed" - plugin version

ChatControl-Red-10.17.7.jar

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

This is a bug with workflow, having a local minecraft server that is on Windows and production on linux, using Github to manage config files between all server(s), as people should be doing.

1. Clone repo onto windows
2. Start Minecraft server and ChatControl Red changes the line endings on all files it opens
3. This makes git see all these files as "changed" when they haven't been changed

This is a separate issue to [comments being removed](https://github.com/kangarko/ChatControl-Red/issues/2315) from files when ChatControl Red is run.

Look top right where I have hovered over the warning.

Line endings should be preserved, I do not have this issue with any other plugin with the same workflow, it must be something to do with the framework you use to manage your config files.

![Screenshot 2023-04-05 12 06 07](https://user-images.githubusercontent.com/144046/230062995-a6838347-d047-4fd6-b130-c6e810125038.png)

**Comment by kangarko** [comment] 2023-04-07 18:01
Interested to see you don't have this problem with other plugins! 

I develop on macOS and Windows and oddly enough never experienced this but I will be sitting down and reproducing for a MC server repo on Monday

**Comment by TomLewis** [comment] 2023-04-07 22:05
MacOS uses the Linux LF, I also have a Macbook and don't have this issue when I use mac! Its only on windows when running the server it converts to CRLF, which is frustrating as I make sure all my files stay as LF, which is respected on Github too.

I can only assume its something to do with the config framework you use auto converting line endings based on the OS instead of keeping them as they are. Ive never had any issues with LF on windows, but then again i'm only doing development work on Windows, not sure anyone would be using it for production... But either way, if people are developing on windows -> copying to Linux servers even without Git the files will change backwards and forwards as they move them! What a mess! 

Thanks for looking into it!

**Comment by kangarko** [comment] 2023-04-09 09:02
Just curious did you try configuring your git repo according to some articles such as this one? https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#configuring-line-endings-in-git-with-coreautocrlf

Turns out you can also use .gitattributes for that, it is covered in the article above.

**Comment by TomLewis** [comment] 2023-04-16 09:51
Yeah, but the plugin is still changing the file line endings when it shouldnt!

**Comment by kangarko** [comment] 2023-04-17 15:38
The final say in saving the file has the config updater library. We need to update it to the latest version first and if you still experience issues just comment below and I will ping its author. There are some problems preventing me from updating, we are resolving them right now.

**Closed as completed by kangarko** 2023-04-17 15:38 UTC

**Comment by TomLewis** [comment] 2024-10-21 21:42
Did this ever get fixed?
![image](https://github.com/user-attachments/assets/72d49125-0826-491d-b47e-6841719c1d93)

**Comment by kangarko** [comment] 2024-10-24 18:07
Do you own any other plugins from us? All other plugins got their library updated, but I cannot guarantee it got fixed since I never could reproduce it anyways.
