### ISSUE TITLE
1.16.4 | if you use msg the player name get dubble

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#56] opened 2020-11-13 07:46 UTC
I has put in msg in alias. But the some how it is broken, it not use the name correct. /tell work fine.

**Comment by kangarko** [comment] 2020-11-13 14:01
Can you please show me a screenshot? Not sure if I understand your problem correctly.

**Comment by broken1arrow** [comment] 2020-11-13 15:10
> Can you please show me a screenshot? Not sure if I understand your problem correctly.

I make a video, easier to understand. 
https://youtu.be/btUUEHyaj30

**Comment by ElBananaa** [comment] 2020-11-13 18:58
I'm pretty sure I had the same issue. Unfortunately, I can't try it again with someone else since my friend isn't available this week-end.

**Comment by broken1arrow** [comment] 2020-11-13 20:46
> I'm pretty sure I had the same issue. Unfortunately, I can't try it again with someone else since my friend isn't available this week-end.

You don´t have a extra account? ;)

**Comment by ElBananaa** [comment] 2020-11-13 22:19
> > I'm pretty sure I had the same issue. Unfortunately, I can't try it again with someone else since my friend isn't available this week-end.
> 
> You don´t have a extra account? ;)

Nope unfortunately xD

**Comment by kangarko** [comment] 2020-11-14 19:20
Sorry I cannot reproduce, is this via Bungee?

I will add "@pm sent" debug messages in the next version, please post them to me when that happens.

**Comment by broken1arrow** [comment] 2020-11-14 22:57
> t



> Sorry I cannot reproduce, is this via Bungee?
> 
> I will add "@pm sent" debug messages in the next version, please post them to me when that happens.

I look like this in console. No Bungee, use /msg broken_arrow1 test and broken_arrow1 get send with the msg as messengers. 

I perhaps need remove the database to fix it (not use mysql, only db file)?

[23:53:51] [Server thread/INFO]: @pm sent to sender Glitzh_
[23:53:51] [Server thread/INFO]: @pm sent to receiver broken_arrow1
[23:53:51] [Server thread/INFO]: [pm] Glitzh_ -> broken_arrow1: broken_arrow1 test

**Comment by ElBananaa** [comment] 2020-11-16 14:26
Hey!

I just noticed that I can PM myself. I think you should add an option like `Self-PM:` to enable/disable this. It can be useful for tests, but it's useless in other cases.

**Comment by kangarko** [comment] 2020-11-16 15:14
Still cannot reproduce, please test the new version and if you will still have that bug, ZIP me your whole CCP folder.

@ElBananaa most people want to also message self, but yeah if many people suggest it we'll add that option :)

**Comment by ElBananaa** [comment] 2020-11-16 15:15
> Still cannot reproduce, please test the new version and if you will still have that bug, ZIP me your whole CCP folder.
> 
> @ElBananaa most people want to also message self, but yeah if many people suggest it we'll add that option :)

Alright, that was just a suggestion. I also tried to reproduce the issue, and I couldn't. Looks like this is something related to his configs.

**Comment by kangarko** [comment] 2020-11-16 15:35
Closing, this should be fixed in the next version, if not send me your ZIP

**Closed as completed by kangarko** 2020-11-16 15:35 UTC
Labels: work-in-progress

**Comment by broken1arrow** [comment] 2020-11-16 15:50
> Hey!
> 
> I just noticed that I can PM myself. I think you should add an option like `Self-PM:` to enable/disable this. It can be useful for tests, but it's useless in other cases.

you can pm you self (at lest a can do it), I think you need a perm for it to work

**Comment by kangarko** [comment] 2020-11-16 16:46
Thanks, but that's not a bug. They both should go to you, that's intended.

**Comment by broken1arrow** [comment] 2020-11-16 21:35
> Thanks, but that's not a bug. They both should go to you, that's intended.

only say to ElBananaa you can send pm to you self :)

But i find the problem, some how have i add the command to replay to :/
