### ISSUE TITLE
1.19: Messages don't delete in-game

### ISSUE THREAD

**Issue by MrLogano** [kangarko/ChatControl#2016] opened 2022-07-25 20:36 UTC
ChatControl-Red Version: 10.12.7
Minecraft Version: 1.19
MySQL: true
BungeeCord: true (Velocity)
All plugins up to date

**Issue:**
When deleting messages, they are deleted in Discord, but not in-game.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9184608/debug.zip)

**Comment by ElBananaa** [comment] 2022-07-26 22:17
Hey,
This is a known issue caused by ProtocolLib 5.x dev builds, on 1.19 version.
I don't know if Kangarko had a chance to take a look at this issue.
@kangarko?

**Comment by kangarko** [comment] 2022-07-31 17:30
Closing and following up here: https://github.com/dmulloy2/ProtocolLib/issues/1796

**Closed as completed by kangarko** 2022-07-31 17:30 UTC

**Comment by kangarko** [comment] 2022-07-31 21:22
Fixed!
