### ISSUE TITLE
1.18.2: Unknown custom packed identifier: plugin:chcred

### ISSUE THREAD

**Issue by rybuilder23** [kangarko/ChatControl#1823] opened 2022-03-27 10:54 UTC
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

When i have the minecraft log book on i get this message

Unknown custom packed identifier: plugin:chcred
( photo )
https://prnt.sc/o-dYRtFaXChX
https://prnt.sc/5XZIr8Rx46H4

and i wonder if this is normal?

**Comment by ElBananaa** [comment] 2022-03-27 15:33
Hey, as said in #1470 this is caused by the client being unable to recognize packets sent from the plugin.

Unfortunately there's nothing we can do about this as far as we know.

**Comment by ElBananaa** [comment] 2022-03-30 19:46
Closing this.
@rybuilder23 Feel free to comment down below if you have any other questions ;)

**Closed as completed by ElBananaa** 2022-03-30 19:46 UTC
