### ISSUE TITLE
Fix [Not Secure] without Prevent_pying

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2124] opened 2022-09-21 16:18 UTC
### Summary

Since Prevent_spying breaks DiscordSRV's mc->dc messages, I cannot use it

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing, except the

**Comment by ElBananaa** [comment] 2022-09-21 16:42
Dupe of #2125, closing.

**Closed as not planned by ElBananaa** 2022-09-21 16:42 UTC
