### ISSUE TITLE
1.16.4 strange symbols in pm yml in formats and motd

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#39] opened 2020-11-12 18:19 UTC
Look like this "&câœ‰ &8[&f{sender} &7-> &f{receiver_or_you}&8] &f{message}" and - "&7- &fAdded ChatControl Redâ„¢ plugin." even ingame.

Not big issue :)

**Comment by ElBananaa** [comment] 2020-11-12 18:22
> Look like this "&câœ‰ &8[&f{sender} &7-> &f{receiver_or_you}&8] &f{message}" and - "&7- &fAdded ChatControl Redâ„¢ plugin." even ingame.
> 
> Not big issue :)

Try to change the file encoding ;)
https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

**Comment by broken1arrow** [comment] 2020-11-12 18:28
> > Look like this "&câœ‰ &8[&f{sender} &7-> &f{receiver_or_you}&8] &f{message}" and - "&7- &fAdded ChatControl Redâ„¢ plugin." even ingame.
> > Not big issue :)
> 
> Try to change the file encoding ;)
> https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

was like this ingame too, I have not touch the files.

**Comment by kangarko** [comment] 2020-11-12 18:45
I am aware of this, still haven't found the cause because it happens sometimes not other times. Keeping open for now. You can remove the [M] icon from the pm format from formats/ folder for now.

**Comment by broken1arrow** [comment] 2020-11-12 18:51
> I am aware of this, still haven't found the cause because it happens sometimes not other times. Keeping open for now. You can remove the [M] icon from the pm format from formats/ folder for now.

I use own format so mostly affects those who do not change format :) I don´t know if it windows some causes this (can try on linux ).

**Comment by kangarko** [comment] 2020-11-12 18:55
Can you try changing encoding? https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

**Comment by ElBananaa** [comment] 2020-11-12 19:06
> Can you try changing encoding? https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

He gave me his config folder, I changed the encoding, and it didn't change anything. Looks like it's something related to the configs since I don't have this issue.

EDIT: Just noticed the caracters are not the right ones inside the files.
E.g. pm-receiver file:

```# -----------------------------------------------------------------------------------------
# The default chat format shown to the receiver of a private message.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message: '&5✉ &8{sender}'
    Hover:
      - '     &8~ &3Private Message &8~     '
      - '&8&oSent {timestamp}'
      - '&3Sender: &f{sender}'
      - '&3Receiver: &f{receiver}'
      - '&3Body: &f{message}'
      - '&aKlicka för att skriva till &9{player_name}'
    Suggest_Command: /msg {player_name}
  Second_Part:
    Message: ' &a☞&6' # He uses an unsupported caracter here.
    Hover:
      - '     &8~ &3Private Message &8~     '
      - '&aKlicka för att telepotera till &9{player_name}'
    Suggest_Command: /tpa {player_name}
  Third_Part:
    Message: ' {receiver}: &d&l{message}'
    Hover:
      - '     &8~ &3Private Message &8~     '
      - '&8&oSent {timestamp}'
      - '&3Sender: &f{sender}'
      - '&3Receiver: &f{receiver}'
      - '&3Body: &f{message}'
      - '&aKlicka för att skriva till &9{player_name}'
    Suggest_Command: /msg {player_name}
```

**Comment by kangarko** [comment] 2020-11-12 19:11
Yeah, there's "☞" which may or may not render in Minecraft

**Comment by broken1arrow** [comment] 2020-11-12 19:12
> Yeah, there's "☞" which may or may not render in Minecraft

is not original file :) I can send the orginals. But look in motd I have not change any thing in that file

**Comment by broken1arrow** [comment] 2020-11-12 19:13
[Uploading formats.zip…]()

**Comment by broken1arrow** [comment] 2020-11-12 19:13
This is file when generated.

**Comment by kangarko** [comment] 2020-11-12 19:15
Your upload is broken, says Uploading formats.zip…, please reupload anew

**Comment by broken1arrow** [comment] 2020-11-12 19:22
[formats.zip](https://github.com/kangarko/ChatControl-Red/files/5532788/formats.zip)

**Comment by ElBananaa** [comment] 2020-11-12 20:02
> Your upload is broken, says Uploading formats.zip…, please reupload anew

New quick update: Just tried to run the plugin under a fresh install on linux, it doesn't happen, but same thing under windows, and this happens. So this is related to the OS

**Comment by broken1arrow** [comment] 2020-11-12 20:30
Nice find of the cause of the error :)

**Comment by kangarko** [comment] 2020-11-14 16:00
Got it. Also confirmed that this happens for Windows only so far (could not get this on Mac). Apologies guys, I have to close this because it's OS-specific. Most servers run on Linux anyways so no big deal.

**Closed as completed by kangarko** 2020-11-14 16:00 UTC
Labels: work-in-progress

**Comment by broken1arrow** [comment] 2020-11-14 17:40
> Got it. Also confirmed that this happens for Windows only so far (could not get this on Mac). Apologies guys, I have to close this because it's OS-specific. Most servers run on Linux anyways so no big deal.

I not see it as big issue either and use normal linux too (but for testing I use local computer and it has windows). If i get more windows specific issues I will switch to Linux.
