### ISSUE TITLE
1.20.4: Latest DiscordSRV incompatibility

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2528] opened 2024-01-05 17:52 UTC
### "/version ChatControlRed" - plugin version

10.23.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/6f774d6695ba4ff8aa0823c659e62d46

### Information about the issue/bug

Update DiscordSRV to 1.27.0

**Comment by kangarko** [comment] 2024-01-06 21:22
Thanks, looking into this asap.

**Comment by kangarko** [comment] 2024-01-06 21:22
Duplicate of https://github.com/kangarko/ChatControl-Red/issues/2527

**Closed as completed by kangarko** 2024-01-06 21:22 UTC
