### ISSUE TITLE
1.19.1: Links that contain a forward slash can't be clicked on.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#2041] opened 2022-08-04 09:55 UTC
### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

Emailed.

### Information about the issue/bug

Purpur dev 1748
ChatControl-Red v10.12.11

URL links in timed messages can't be clicked on if they extend past the first line.

Can be clicked on.
![link](https://i.imgur.com/iTT4VQD.png)

Can't be clicked on.
![link2](https://i.imgur.com/9jtYTCT.png)

Can't be clicked on.
![link3](https://i.imgur.com/eD098KE.png)

**Comment by TheIntolerant** [comment] 2022-08-04 11:14
Check out this to see if that fixes your issue.
![image](https://user-images.githubusercontent.com/48093184/182834169-0f540f7f-8b6d-44a0-9094-fe01f4296af3.png)
https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#the-url-in-my-messages-are-not-clickable

**Comment by mibby** [comment] 2022-08-05 09:15
Adding `` &r`` after the link does not fix the issue. Nor does adding it before the link. The URL detection just simply breaks when it reaches a new line in the output.

**Comment by TheIntolerant** [comment] 2022-08-05 09:40
After some quick test it seems this affects URL links that contain a forward slash, most likely caused by changes seen here kangarko/Foundation@1103edcfd425896c92cf429e15cb0fb37f820816

**Comment by TheIntolerant** [comment] 2022-08-05 09:42
Typing
``example.com`` in chat is clickable, the same for any timed messages etc
``example.com/test`` or any link with a forward slash is no longer clickable.

This can be tested by either typing into chat (as long as channels are enabled) or using timed messages etc.

I'm sure once @kangarko or @ElBananaa have a look at this, one of them will make changes as needed to fix this issue.

**Comment by ElBananaa** [comment] 2022-08-05 17:47
Hey, this has been fixed in https://github.com/kangarko/Foundation/pull/177.
I tested it, and I ensured we can detect more complex urls such as (`http(s)://`and/or`www.`)`google.com/this/is/a/test/url/12548#test`
Next version should hopefully include the fix.

However, as it seems like Kangarko's mcmarket account has been suspended (I don't know why/for howlong), simply let me know if you need the patch now, and i'll send it on discord directly.

**Closed as completed by ElBananaa** 2022-08-05 17:47 UTC

**Comment by mibby** [comment] 2022-08-07 23:25
> simply let me know if you need the patch now, and i'll send it on discord directly.

It would be nice to have it early. If you happen to have the time and can send a preview build with the fix in, it would be much appreciated. I did try reaching out to you in the MineAcademy discord and your dms are off to non-friends.

**Comment by kangarko** [comment] 2022-08-08 13:34
Thanks, I will release this as a public release in a few days. I am not looking at creating developer builds at the moment, we have weekly plugin updates which is quite fast already.
