### ISSUE TITLE
1.20.1: Chain link failed - error message in console

### ISSUE THREAD

**Issue by BijuuKrunos** [kangarko/ChatControl#2494] opened 2023-11-18 10:18 UTC
### "/version ChatControlRed" - plugin version

10.22.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/f886e567a6ca49cba9b1e9fc465a95e2

### Information about the issue/bug

Every time a player is writing into the chat instead of the written message this error is seen in console on the server where the player was wrting (On other bungee connected servers, the message is in the console not the error.
Using ViaVersion on the paper Servers.
Send you the debug.zip via mail.

**Comment by kangarko** [comment] 2023-11-19 19:19
Hey Krunos!

Are you using Folia btw? It says Paper in your debug but just in case.

Anyhow, it really does not look like ChatControl, but it might disappear when you delete it since from my memory this issue comes from the Conversation API which we use, and it's a part of Bukkit.

Have you tried without ProtocolLib / ViaVersion by any chance? Just to check whether it will persist.

**Comment by BijuuKrunos** [comment] 2023-11-19 20:16
> Hey Krunos!
> 
> Are you using Folia btw? It says Paper in your debug but just in case.
> 
> Anyhow, it really does not look like ChatControl, but it might disappear when you delete it since from my memory this issue comes from the Conversation API which we use, and it's a part of Bukkit.
> 
> Have you tried without ProtocolLib / ViaVersion by any chance? Just to check whether it will persist.

Hello Kangarko,

yes i am using paper-1.20.1-196 no Folia.

Tested without Viaversion and Protocollib = still the same issue.
Tested without ChatControl = No error message.

So pretty sure it has something todo with Chatcontrol :)

thanks for helping

**Comment by kangarko** [comment] 2023-11-20 09:37
The error log above does not mention my plugin at all. Unless you provide a stack trace with chatcontrol on it I am unable to reproduce because it's impossible to trace the issue.

I tried googling this issue but [only found three articles](https://www.google.com/search?q=%22Chain+link+failed%2C+continuing+to+next+one%22&gl=us&hl=all), one by myself regarding Folia breaking some APIs, hence my above question.

Try setting Integration.ProtocolLib.Listen_For_Packets to false in settings.yml

If that won't help, try on a test server with only ChatControl plugin present and no other plugins.

Finally, try asking on Paper Discord without using ProtocolLib or any other packet-modification plugin.

**Comment by BijuuKrunos** [comment] 2023-11-20 12:02
Yeah didnot find anything as well.
Disabled Listen_for_packets in settings = no changes.
Updated to newest paper 1.20.2 297 = no changes
Removed all plugins except chatcontrol and luckperms = still no changes.

(Everything on a copy from my Main Network (Copied Virtual Machine ;) )

If you dont have any idea i would try to ask paper if they have any.

**Comment by BijuuKrunos** [comment] 2023-11-20 15:04
![image](https://github.com/kangarko/ChatControl-Red/assets/38471938/4af00949-bb70-43aa-8bea-01f8c87bf417)
thats the reply from paper

**Comment by kangarko** [comment] 2023-11-20 17:46
How can I reproduce this? I booted up your debug but it won't kick me. Connected through bungee with mysql on:

![a](https://i.imgur.com/C8Q2AYD.png)

**Comment by BijuuKrunos** [comment] 2023-11-20 18:11
thats the 100 Dollar Question haha. And i dont get kicked, the error just appears in the console the moment where i wrote something in chat.

**Comment by kangarko** [comment] 2023-11-21 06:52
Does it happen for every player consistently while typing any message in the chat or just for you? Does it happen for all channels or a specific one? Can you send a screenshot of you sending a message how it appears on the screen when the error gets printed?

**Comment by BijuuKrunos** [comment] 2023-11-21 08:05
For every Player who sents an regular Message, so for us a Bungee Message. Mhh Needs to check if its happening for /msg as well.
on every message (But only on the Paper Server where the Player is on and sending the Message, on the other paper Servers, where a Player is just receiving the message, it does not happen.

For Bungee Channel (Our normal), not tested for msg yet.

The Message in game is completely fine and as it should, just in the console the message is not printed, only the error.
if needed i can provide screenshots later.

**Comment by kangarko** [comment] 2023-11-21 17:47
Can you try toggling the option Channels.Alternative_Console_Sending in settings.yml?

**Comment by BijuuKrunos** [comment] 2023-11-21 20:31
Ohh lol, yeah that worked. haha
edited to true

**Comment by kangarko** [comment] 2023-11-22 19:21
Thanks for letting me know, closing this.

**Closed as completed by kangarko** 2023-11-22 19:21 UTC
