### ISSUE TITLE
1.18.2: Chat Format Issue

### ISSUE THREAD

**Issue by Suinalk** [kangarko/ChatControl#1859] opened 2022-04-22 11:44 UTC
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: false

Basically, I have a lot of ranks in "chat.yml" and the problem is that I need to go to luckperms and negate "Sender_Permission: rank.admin or rank.vip and so on" if I don't... It literally spams the whole chat. I have to like negate everything on every new rank I make which is a pain... Am I doing something wrong?
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8540643/debug.zip)

**Comment by Suinalk** [comment] 2022-04-22 11:47
![image](https://user-images.githubusercontent.com/56520087/164708563-3c07f4fb-ad34-40ac-807b-98968320647a.png)
If I don't do that on myself... It would look like this...
![image](https://user-images.githubusercontent.com/56520087/164708666-c5bd1928-48a6-4aad-a52e-d986a338a4e7.png)

**Comment by ElBananaa** [comment] 2022-04-22 13:41
Hey,
This is most likely caused by the fact that you either have the `*` permission and/or because your rank inherits from all the other ranks.
In both cases, negating the permissions of the previous ranks as you did will solve the issue.

**Comment by TheIntolerant** [comment] 2022-04-22 13:58
You could also choose to manage prefixes/suffixes in LuckPerms itself instead of using a format file in chatcontrol to manage prefixes, for more info read [prefix meta](https://luckperms.net/wiki/Meta-Commands#lp-usergroup-usergroup-meta-setprefix-priority-prefix-context). That way you don't need to go thru this process of negating the permission nodes.

If you do opt to manage prefixes via LuckPerms and you have mutiple types of prefixes that a user should have, you may want to also read [prefix/suffix stacking](https://luckperms.net/wiki/Prefix-&-Suffix-Stacking).

**Comment by Suinalk** [comment] 2022-04-22 14:09
I feel like it gives more control when I do it in chatcontrol...

**Comment by Suinalk** [comment] 2022-04-22 14:29
Omg so negating is something I'll have to do omagash

**Comment by Suinalk** [comment] 2022-04-22 14:35
That's going to be annoying o man

**Comment by Suinalk** [comment] 2022-04-22 14:36
Well I guess there is no other way around it so :I

**Comment by TheIntolerant** [comment] 2022-04-23 00:11
While it is possible to make a workaround with the "sender_condition" this would require you have some knowledge with JavaScript to create a variable that works effectively for this particular case.

Otherwise, yes, negating each permission is the only way around this. Closing this issue since it's been resolved but feel free to comment below if you have any additional questions.

**Closed as completed by TheIntolerant** 2022-04-23 00:11 UTC
