### ISSUE TITLE
1.16:4| or 1.17 ;) cant set Receiver_Permission: if you use placeholder

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#373] opened 2020-12-25 13:53 UTC
It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and  Sender_Permission).  do not know if it is bug or deliberately done. 

One example i try:

```
  Third_Part:
    Message: '&e{message}'
    Receiver_Permission: chatcontrol.hjelp

```
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment] 2020-12-25 16:10
> It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> 
> One example i try:
> 
> ```
>   Third_Part:
>     Message: '&e{message}'
>     Receiver_Permission: chatcontrol.hjelp
> ```
> 
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false

Hey! Merry Christmas!
Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.

**Comment by broken1arrow** [comment] 2020-12-25 22:40
> > It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> > One example i try:
> > ```
> >   Third_Part:
> >     Message: '&e{message}'
> >     Receiver_Permission: chatcontrol.hjelp
> > ```
> > 
> > 
> > Minecraft Version: 1.16.4
> > MySQL: false
> > BungeeCord: false
> 
> Hey! Merry Christmas!
> Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.

yes here it is.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742469/debug.zip)

**Comment by ElBananaa** [comment] 2020-12-25 23:23
> > > It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> > > One example i try:
> > > ```
> > >   Third_Part:
> > >     Message: '&e{message}'
> > >     Receiver_Permission: chatcontrol.hjelp
> > > ```
> > > 
> > > 
> > > Minecraft Version: 1.16.4
> > > MySQL: false
> > > BungeeCord: false
> > 
> > 
> > Hey! Merry Christmas!
> > Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.
> 
> yes here it is.
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742469/debug.zip)

Thanks! I just tried on my test server with this code, and it works fine, the message part is sent even if I don't have the permission, but I can't see it. If I have the permission, I can see it.
I used this code: 
```
  message:
    Message: '&8&l» &r{message}'
    Sender_Permission: chatcontrol.sendchatmessage
```

Of course, the receiver permission is ignored if you are the one who sent the message, and this is normal: It's your message, so it makes sense that you will see your own messages, even if you don't have the permission for.

If that's all, can I close this issue?

**Comment by broken1arrow** [comment] 2020-12-25 23:48
> > > > It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> > > > One example i try:
> > > > ```
> > > >   Third_Part:
> > > >     Message: '&e{message}'
> > > >     Receiver_Permission: chatcontrol.hjelp
> > > > ```
> > > > 
> > > > 
> > > > Minecraft Version: 1.16.4
> > > > MySQL: false
> > > > BungeeCord: false
> > > 
> > > 
> > > Hey! Merry Christmas!
> > > Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.
> > 
> > 
> > yes here it is.
> > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742469/debug.zip)
> 
> Thanks! I just tried on my test server with this code, and it works fine, the message part is sent even if I don't have the permission, but I can't see it. If I have the permission, I can see it.
> I used this code:
> 
> ```
>   message:
>     Message: '&8&l» &r{message}'
>     Sender_Permission: chatcontrol.sendchatmessage
> ```
> 
> Of course, the receiver permission is ignored if you are the one who sent the message, and this is normal: It's your message, so it makes sense that you will see your own messages, even if you don't have the permission for.
> 
> If that's all, can I close this issue?

Will test it more, but is not the sender it get problem. Every one some not has the perm can see this too, when it is send and player i test this is not op or has any bypass perms.

If I remove the message placeholder it work fine.

**Comment by ElBananaa** [comment] 2020-12-26 01:05
> > > > > It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> > > > > One example i try:
> > > > > ```
> > > > >   Third_Part:
> > > > >     Message: '&e{message}'
> > > > >     Receiver_Permission: chatcontrol.hjelp
> > > > > ```
> > > > > 
> > > > > 
> > > > > Minecraft Version: 1.16.4
> > > > > MySQL: false
> > > > > BungeeCord: false
> > > > 
> > > > 
> > > > Hey! Merry Christmas!
> > > > Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.
> > > 
> > > 
> > > yes here it is.
> > > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742469/debug.zip)
> > 
> > 
> > Thanks! I just tried on my test server with this code, and it works fine, the message part is sent even if I don't have the permission, but I can't see it. If I have the permission, I can see it.
> > I used this code:
> > ```
> >   message:
> >     Message: '&8&l» &r{message}'
> >     Sender_Permission: chatcontrol.sendchatmessage
> > ```
> > 
> > 
> > Of course, the receiver permission is ignored if you are the one who sent the message, and this is normal: It's your message, so it makes sense that you will see your own messages, even if you don't have the permission for.
> > If that's all, can I close this issue?
> 
> Will test it more, but is not the sender it get problem. Every one some not has the perm can see this too, when it is send and player i test this is not op or has any bypass perms.
> 
> If I remove the message placeholder it work fine.

Ok so basically, even if the players don't have the receiver_permission, they still can see the message. 

That's pretty weird. As I said above, I tested on my own server, and I couldn't reproduce this issue. Could you tell me in which format file you use this part?
If I understand correctly what you wrote, you didn't give any permission, so try to deny the permission instead of not giving it (If you are using luckperms, set the permission to `false`). Does it change anything?

**Comment by broken1arrow** [comment] 2020-12-26 08:04
> > > > > > It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> > > > > > One example i try:
> > > > > > ```
> > > > > >   Third_Part:
> > > > > >     Message: '&e{message}'
> > > > > >     Receiver_Permission: chatcontrol.hjelp
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Minecraft Version: 1.16.4
> > > > > > MySQL: false
> > > > > > BungeeCord: false
> > > > > 
> > > > > 
> > > > > Hey! Merry Christmas!
> > > > > Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.
> > > > 
> > > > 
> > > > yes here it is.
> > > > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742469/debug.zip)
> > > 
> > > 
> > > Thanks! I just tried on my test server with this code, and it works fine, the message part is sent even if I don't have the permission, but I can't see it. If I have the permission, I can see it.
> > > I used this code:
> > > ```
> > >   message:
> > >     Message: '&8&l» &r{message}'
> > >     Sender_Permission: chatcontrol.sendchatmessage
> > > ```
> > > 
> > > 
> > > Of course, the receiver permission is ignored if you are the one who sent the message, and this is normal: It's your message, so it makes sense that you will see your own messages, even if you don't have the permission for.
> > > If that's all, can I close this issue?
> > 
> > 
> > Will test it more, but is not the sender it get problem. Every one some not has the perm can see this too, when it is send and player i test this is not op or has any bypass perms.
> > If I remove the message placeholder it work fine.
> 
> Ok so basically, even if the players don't have the receiver_permission, they still can see the message.
> 
> That's pretty weird. As I said above, I tested on my own server, and I couldn't reproduce this issue. Could you tell me in which format file you use this part?
> If I understand correctly what you wrote, you didn't give any permission, so try to deny the permission instead of not giving it (If you are using luckperms, set the permission to `false`). Does it change anything?

No, is not help. Is is hjalp.yml i playing with.

This part work fine, seams bee something when i use message placeholder. 

```
  delete-chat:
    Message: '&8[&4X&8] &f'
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cRemove this message from chat for all players.'
```

**Comment by ElBananaa** [comment] 2020-12-26 16:59
> > > > > > > It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> > > > > > > One example i try:
> > > > > > > ```
> > > > > > >   Third_Part:
> > > > > > >     Message: '&e{message}'
> > > > > > >     Receiver_Permission: chatcontrol.hjelp
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > Minecraft Version: 1.16.4
> > > > > > > MySQL: false
> > > > > > > BungeeCord: false
> > > > > > 
> > > > > > 
> > > > > > Hey! Merry Christmas!
> > > > > > Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.
> > > > > 
> > > > > 
> > > > > yes here it is.
> > > > > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742469/debug.zip)
> > > > 
> > > > 
> > > > Thanks! I just tried on my test server with this code, and it works fine, the message part is sent even if I don't have the permission, but I can't see it. If I have the permission, I can see it.
> > > > I used this code:
> > > > ```
> > > >   message:
> > > >     Message: '&8&l» &r{message}'
> > > >     Sender_Permission: chatcontrol.sendchatmessage
> > > > ```
> > > > 
> > > > 
> > > > Of course, the receiver permission is ignored if you are the one who sent the message, and this is normal: It's your message, so it makes sense that you will see your own messages, even if you don't have the permission for.
> > > > If that's all, can I close this issue?
> > > 
> > > 
> > > Will test it more, but is not the sender it get problem. Every one some not has the perm can see this too, when it is send and player i test this is not op or has any bypass perms.
> > > If I remove the message placeholder it work fine.
> > 
> > 
> > Ok so basically, even if the players don't have the receiver_permission, they still can see the message.
> > That's pretty weird. As I said above, I tested on my own server, and I couldn't reproduce this issue. Could you tell me in which format file you use this part?
> > If I understand correctly what you wrote, you didn't give any permission, so try to deny the permission instead of not giving it (If you are using luckperms, set the permission to `false`). Does it change anything?
> 
> No, is not help. Is is hjalp.yml i playing with.
> 
> This part work fine, seams bee something when i use message placeholder.
> 
> ```
>   delete-chat:
>     Message: '&8[&4X&8] &f'
>     Receiver_Permission: chatcontrol.removemessages
>     Hover:
>     - '&cRemove this message from chat for all players.'
> ```

Ok, well, it seems pretty weird. You'll have to wait for Kangarko so he can take a look at this issue.
Also, I think you shouldn't use any special caracters for the identifiers:
```
    mc-hjälp:
      Format: hjalp
      Format_Console: '&9MC-hjälp-&f{player}: &9{message}'
      Discord: true
```
Instead, use:
```
    mc-hjalp:
      Format: hjalp
      Format_Console: '&9MC-hjälp-&f{player}: &9{message}'
      Discord: true
```

**Comment by broken1arrow** [comment] 2020-12-26 19:17
> > > > > > > > It ignore perm needed for read a msg if you use {message} placeholder (has only test Receiver_Permission and Sender_Permission). do not know if it is bug or deliberately done.
> > > > > > > > One example i try:
> > > > > > > > ```
> > > > > > > >   Third_Part:
> > > > > > > >     Message: '&e{message}'
> > > > > > > >     Receiver_Permission: chatcontrol.hjelp
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Minecraft Version: 1.16.4
> > > > > > > > MySQL: false
> > > > > > > > BungeeCord: false
> > > > > > > 
> > > > > > > 
> > > > > > > Hey! Merry Christmas!
> > > > > > > Could you please provide your `/chc debug` file? I'll run some tests to see if I can reproduce this issue.
> > > > > > 
> > > > > > 
> > > > > > yes here it is.
> > > > > > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742469/debug.zip)
> > > > > 
> > > > > 
> > > > > Thanks! I just tried on my test server with this code, and it works fine, the message part is sent even if I don't have the permission, but I can't see it. If I have the permission, I can see it.
> > > > > I used this code:
> > > > > ```
> > > > >   message:
> > > > >     Message: '&8&l» &r{message}'
> > > > >     Sender_Permission: chatcontrol.sendchatmessage
> > > > > ```
> > > > > 
> > > > > 
> > > > > Of course, the receiver permission is ignored if you are the one who sent the message, and this is normal: It's your message, so it makes sense that you will see your own messages, even if you don't have the permission for.
> > > > > If that's all, can I close this issue?
> > > > 
> > > > 
> > > > Will test it more, but is not the sender it get problem. Every one some not has the perm can see this too, when it is send and player i test this is not op or has any bypass perms.
> > > > If I remove the message placeholder it work fine.
> > > 
> > > 
> > > Ok so basically, even if the players don't have the receiver_permission, they still can see the message.
> > > That's pretty weird. As I said above, I tested on my own server, and I couldn't reproduce this issue. Could you tell me in which format file you use this part?
> > > If I understand correctly what you wrote, you didn't give any permission, so try to deny the permission instead of not giving it (If you are using luckperms, set the permission to `false`). Does it change anything?
> > 
> > 
> > No, is not help. Is is hjalp.yml i playing with.
> > This part work fine, seams bee something when i use message placeholder.
> > ```
> >   delete-chat:
> >     Message: '&8[&4X&8] &f'
> >     Receiver_Permission: chatcontrol.removemessages
> >     Hover:
> >     - '&cRemove this message from chat for all players.'
> > ```
> 
> Ok, well, it seems pretty weird. You'll have to wait for Kangarko so he can take a look at this issue.
> Also, I think you shouldn't use any special caracters for the identifiers:
> 
> ```
>     mc-hjälp:
>       Format: hjalp
>       Format_Console: '&9MC-hjälp-&f{player}: &9{message}'
>       Discord: true
> ```
> 
> Instead, use:
> 
> ```
>     mc-hjalp:
>       Format: hjalp
>       Format_Console: '&9MC-hjälp-&f{player}: &9{message}'
>       Discord: true
> ```

I try to not use åäö in this spots, but some times i miss it :)

**Comment by kangarko** [comment] 2020-12-30 12:48
Thanks, I fixed that.

**Closed as completed by kangarko** 2020-12-30 12:48 UTC
