### ISSUE TITLE
1.16.4: {rule_name} not working

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#457] opened 2021-01-01 16:07 UTC
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

I have set a group with then notify and the {rule_name} placeholder, but it dont get replaced. Screenshot: https://prnt.sc/we77d2

**Comment by ElBananaa** [comment] 2021-01-01 16:43
Hey!
Happy New Year!

Thanks for reporting this issue. However, I tried to reproduce it, and I couldn't.
Please make sure that your plugins, your server software and your dependencies are all up-to-date.
In order to get the {rule_name} placeholder, you must define a name to the desired rule.

I'm closing this issue, let me know down below if you need anything else.

**Comment by DevJoey** [comment] 2021-01-01 17:21
Iam running the newest version from chc on mcmarket all is up to date. and the rules have names. i use this in groups, so if you use {rule_name} in groups it not works. it gets also not replaced in then write files/name.log

**Comment by DevJoey** [comment] 2021-01-01 17:25
Here my group: https://prnt.sc/we8dem
Here The rules: https://prnt.sc/we8dsl

**Comment by ElBananaa** [comment] 2021-01-03 15:56
Hey!

Sorry for the delays, I forgot to answer you.
I tested this on a local server, and I could reproduce the issue.
Since I don't know if this is intended or not, I'll leave this ticket open so Kangarko could take a look at it.

**Comment by kangarko** [comment] 2021-01-07 17:18
For groups, use {group_name} instead 👍

**Closed as completed by kangarko** 2021-01-07 17:18 UTC

**Comment by DevJoey** [comment] 2021-01-07 18:11
> 
> 
> For groups, use {group_name} instead 👍

But will it show the rule wich is triggered. so i can identity the sigle rule? it would be nice if there is a placeholder which shows the rule that triggers that group

**Comment by kangarko** [comment] 2021-01-08 08:53
Thanks will add
