### ISSUE TITLE
1.18.1: multipul "NumberFormatException" within settings.yml

### ISSUE THREAD

**Issue by Terminal-Access** [kangarko/ChatControl#1598] opened 2022-01-01 19:46 UTC
**Minecraft Version:** 1.18.1
**Server Version:** paper-1.18.1-120 and above.
**Chat Control Red Version:** 10.8.9
**MySQL:** False
**BungeeCord:** False

**Note:** This bug dose not occur when using  paper-1.18.1-119 or below!

Hey guys i seem to be getting a lot of "NumberFormatException" error aftert recently updating CCR to it's latest version "10.8.9 as of the time of this bug report"

Quick Snippet for ease of reading.
```
Error loading configuration in settings.yml!
Problematic section: Warning_Points.Reset_Task
Problem: java.lang.NumberFormatException: For input string: "org.bukkit.configuration.SectionPathData@346e5cbe" (see below for more)
NumberFormatException For input string: "org.bukkit.configuration.SectionPathData@346e5cbe"
```

Was unable to perform the /chc debug command as the plugin is disabled due to the errors present.

Below I have included both the error.log file and my settings.yml file for review.

[error.log](https://pastebin.com/tdXMD5wW)

[settings.yml](https://pastebin.com/hh9QGnjK)

If anything else is needed please let me know and ill provide asap.

Cheers
Lee.

**Comment by Terminal-Access** [comment] 2022-01-01 19:53
**Note:** As of paper 1.18.1 build 120 - "[[3a43821]](https://github.com/PaperMC/Paper/commit/3a43821c382ed99b3e64892381c263a23e9cc56a) Updated Upstream (Bukkit/CraftBukkit/Spigot)"

I believe this may be where the bug is arising from as version prior to this do not have these issues.

**Comment by ElBananaa** [comment] 2022-01-01 21:49
> **Note:** As of paper 1.18.1 build 120 - "[[3a43821]](https://github.com/PaperMC/Paper/commit/3a43821c382ed99b3e64892381c263a23e9cc56a) Updated Upstream (Bukkit/CraftBukkit/Spigot)"
> 
> I believe this may be where the bug is arising from as version prior to this do not have these issues.

Hey, Happy New Year!
Thanks for reporting this and running extended tests. I already reported this to Kangarko, so this will hopefully be fixed in the next few days. ;)
![image](https://user-images.githubusercontent.com/53318613/147860848-d2fd3625-cb6f-4958-b9c5-1133621144b6.png)

**Comment by Terminal-Access** [comment] 2022-01-01 23:32
Happy new year, and cheers for the update xD

**Comment by x1p** [comment] 2022-01-02 10:10
If I only had known this before updating...

**Comment by Godlycreations** [comment] 2022-01-02 14:29
I can also confirm this issue. I was updating to the latest paperMC build when CHC red stopped working. I just downgraded paperMC and the issue resolved itself. So just wait to update paperMC until CHC red has been updated to work with the latest builds. Continue to keep up the great work on this plugin!!!

**Comment by Terminal-Access** [comment] 2022-01-02 16:51
**Minor Informational Update:**  

Technically this does not have to do with Chat Control Red, however just wanted to note I've seen Chat Control Pro users (via discord) also be affected with this, Just so we know the issue affect both plugins.

**Comment by ElBananaa** [comment] 2022-01-02 16:57
> **Minor Informational Update:**
> 
> Technically this does not have to do with Chat Control Red, however just wanted to note I've seen Chat Control Pro users (via discord) also be affected with this, Just so we know the issue affect both plugins.

Hey, thanks!
We do know issues currently affects all of Kangarko's plugins. This is caused by the fact that the changes made in b120 broke a few things in Foundation, which is kangarko's core library ^^

**Comment by VimaMT** [comment] 2022-01-03 14:12
This is causing my Chatcontrol to be disabled. I tried to put an old version in (10.8.6), and I have the same issues. Could this be related to a recent Paper update?

**Comment by Terminal-Access** [comment] 2022-01-03 14:20
> This is causing my Chatcontrol to be disabled. I tried to put an old version in (10.8.6), and I have the same issues. Could this be related to a recent Paper update?

Yes this is caused by an upstream.update since paper build 120.


please use paper build 119 untill the plugin has been updated.

**Comment by kangarko** [comment] 2022-01-03 14:56
Thanks guys, we'll update all plugins tonight including ChatControl Pro since this is a critical update.

**Comment by kangarko** [comment] 2022-01-03 14:57
And happy new year :))

**Closed as completed by kangarko** 2022-01-03 14:56 UTC
