### ISSUE TITLE
1.18.2: Private Message Inconsistencies

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl#1827] opened 2022-03-28 19:07 UTC
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

It seems like there is no {sender_nick} variable for the pm_reciever format, while the pm_sender format does support a {receiver_nick} variable. Am I missing something here? 

Additionally, it doesn't seem like the GUI color selected by the player applies to messages in pms.

Thanks for your time.

**Comment by TheIntolerant** [comment] 2022-03-28 19:53
Regarding the nick placeholder for the "sender", I believe you should be able to just use `{nick}`

**Comment by Leomelonseeds** [comment] 2022-03-28 22:51
Ah, seems like that does work, thank you very much!

**Comment by ElBananaa** [comment] 2022-03-30 19:56
> Ah, seems like that does work, thank you very much!

Hey, sorry for the delay.
Thanks to TheIntolerant for answering your first question.

As for the 2nd part, this is an intended behavior.
You can easily get player's chat color and decoration by using the `{chat_color}` and `{chat_decoration}` placeholders in the `pm_receiver` and `pm_sender` format files. (More informations on our wiki page https://github.com/kangarko/ChatControl-Red/wiki/Variables#native-variables)

I'm closing this issue, but feel free to comment down below if you have any other questions related to these ones, or open a new issue if you need anything else! ;)

**Closed as completed by ElBananaa** 2022-03-30 19:56 UTC
