### ISSUE TITLE
1.16.5 format chat from discord to minecraft

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1234] opened 2021-08-14 23:29 UTC
Hi there,

How to format the ingame chat when i send a message from discord to my ingame chat?

I am able to format the messages that are being send FROM minecraft TO discord. Now i am trying to find a way to format the messages that are being send FROM discord TO minecraft.

my channels below: ive linked the admin channel to my discord and gave it the format: "Format_Discord: '{server_name} {player}: {message}'"
![image](https://user-images.githubusercontent.com/10013800/129462565-a0f63ed1-aef3-462e-a446-83691e930deb.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by donvdp** [comment] 2021-08-14 23:36
The way i understand the functionality is that::
![image](https://user-images.githubusercontent.com/10013800/129462697-70fb0317-9ce9-4b89-85f4-1d8652949eda.png)
The "admin-chat.yml" file contains the formatting of the adminchannel in the minecraft game. so is there a setup that i can use inside the "admin-chat.yml" file so that i can format a message from discord to minecraft?

Perhaps anyone here has an example ?

**Comment by ElBananaa** [comment] 2021-08-15 00:25
> Hi there,
> 
> How to format the ingame chat when i send a message from discord to my ingame chat?
> 
> I am able to format the messages that are being send FROM minecraft TO discord. Now i am trying to find a way to format the messages that are being send FROM discord TO minecraft.
> 
> my channels below: ive linked the admin channel to my discord and gave it the format: "Format_Discord: '{server_name} {player}: {message}'"
> ![image](https://user-images.githubusercontent.com/10013800/129462565-a0f63ed1-aef3-462e-a446-83691e930deb.png)
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
I believe the format used for messages sent on discord to minecraft is the one used for the channel itself.
If you'd like to use a specific format dedicated to discord, you could play with the `Sender_Condition` and `Sender_Condition`.
So here's an example:

```yaml
Parts:
#All parts starting with "global"- won't need the `Require_Sender` or `Require_Receiver` argument because they are shown wether the sender is a discord user or an ingame player.
  global-delete-chat:
    Message: '&7[#cf0e00&lX&7] '
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cClick to delete this message.'
    Run_Command: /{label} internal remove {message_uuid}

#All parts starting with "minecraft-" will only be shown when a player sends a messages from the game.
  minecraft-report-player:
    Message: '&c⚠ '
    Sender_Permission: chatcontrol.allowreport
    Sender_Condition: '{sender_is_player} == true'
    Receiver_Permission: chatcontrol.allowreport
    Hover:
    - '&e&lClick to report &c{player}&e.'
    Suggest_Command: /report {player}
  minecraft-spy-prefix:
    Message: '&c&lSPY&8&l| '
    Sender_Condition: '{sender_is_player} == true'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover:
    - '&cClick to stop spying the &e{channel}&c channel.'
    Run_Command: /{label_spy} toggle chat {channel}
  minecraft-prefix:
    Message: '{player_prefix}'
    Sender_Condition: '{sender_is_player} == true'
    Hover:
    - '&7{player_prefix}{player_name} {player_suffix}'
    - ''
    - '&cClick to open our website.'
    Open_Url: https://google.com
  minecraft-player-nick:
    Message: '{player_nick} '
    Sender_Condition: '{sender_is_player} == true'
    Hover:
    - '&7First Join: &f{player_first_join_date}'
    - ''
    - '&c&nClick to DM'
    Suggest_Command: '/tell {player_name} '

#All parts starting with "discord-" will only be shown when a player sends a messages from discord.
  discord-prefix:
    Message: '&7[&cDiscord] '
    Sender_Condition: '{sender_is_player} == false'
  discord-player-name:
    Message: '{player} '
    Sender_Condition: '{sender_is_player} == false'

  global-message:
    Message: '&8&l» &r{message}'
    Hover:
    - '&7Date: &b{timestamp}'
```

**Comment by donvdp** [comment] 2021-08-15 11:08
Hey cool example. thanks for this, I have tried to figure out a way to set this up and went to the ChatControlRed wiki page:
- https://github.com/kangarko/ChatControl-Red/wiki/formats
- https://github.com/kangarko/ChatControl-Red/wiki/Variables

There i saw a variable called "{sender_is_discord}" and attempted to use this in my chat formatting. Here is what i came up with.

my admin-chat.yml file:

```
# The parts of this format.
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  
  Prefix-StaffChat:
    Message: '&4[Staff Chat] '

  #discord prefix of anders de server waarop het is verstuurd
  Discord-prefix:
    Message: '[discord] '
    Sender_Condition: '{sender_is_discord} == true'

  Server-prefix:
    Message: '&3{server_name} '
    Sender_Condition: '{sender_is_player} == true'

  SpelerNaam:
    Message: '&c{player_name}'

  message:
    Message: '&b: {message}'
```

basicly what im trying to make is an 
"if -senderdiscord- then 
   -use discord prefix- 
else 
   -use server prefix- 
endif" 
statement.


I dont think the "Sender_Condition" part is working properly, because ingame i get an message containing both the discord prefix AND the server prefix. 
![image](https://user-images.githubusercontent.com/10013800/129476378-ea2987ac-216a-4dea-8656-300c8d25f659.png)

**Comment by ElBananaa** [comment] 2021-08-15 13:59
> Hey cool example. thanks for this, I have tried to figure out a way to set this up and went to the ChatControlRed wiki page:
> 
> * https://github.com/kangarko/ChatControl-Red/wiki/formats
> * https://github.com/kangarko/ChatControl-Red/wiki/Variables
> 
> There i saw a variable called "{sender_is_discord}" and attempted to use this in my chat formatting. Here is what i came up with.
> 
> my admin-chat.yml file:
> 
> ```
> # The parts of this format.
> Parts:
>   
>   # See the chat.yml format file for a tutorial on how this works.
>   
>   Prefix-StaffChat:
>     Message: '&4[Staff Chat] '
> 
>   #discord prefix of anders de server waarop het is verstuurd
>   Discord-prefix:
>     Message: '[discord] '
>     Sender_Condition: '{sender_is_discord} == true'
> 
>   Server-prefix:
>     Message: '&3{server_name} '
>     Sender_Condition: '{sender_is_player} == true'
> 
>   SpelerNaam:
>     Message: '&c{player_name}'
> 
>   message:
>     Message: '&b: {message}'
> ```
> 
> basicly what im trying to make is an
> "if -senderdiscord- then
> -use discord prefix-
> else
> -use server prefix-
> endif"
> statement.
> 
> I dont think the "Sender_Condition" part is working properly, because ingame i get an message containing both the discord prefix AND the server prefix.
> ![image](https://user-images.githubusercontent.com/10013800/129476378-ea2987ac-216a-4dea-8656-300c8d25f659.png)

Hey!
The Sender_Condition workd fine. The issue is with the {sender_is_discord} placeholder which is broken. Kangarko is aware of it, but he didn't have the time to look at it yet. That's why I used {sender_is_player} in my example, instead of it.

**Comment by donvdp** [comment] 2021-08-16 06:50
Well what you are suggesting isnt working either. I still get both prefixes in the same sentence.

Perhaps it would be a good idea to fix the bugg that is causing this error ? having the variable {sender_is_discord} would be the best way to go i think ?

**Comment by ElBananaa** [comment] 2021-08-16 15:59
Hi,
If your server is running Java 15+, please (That's up to you to decide if you want to do it, of course, but our wiki page clearly says that NashornPlus is needed for servers using java 15+ : https://github.com/kangarko/ChatControl-Red/wiki/Compatibility) make sure NashornPlus (https://mineacademy.org/nashorn/) is installed, and up-to-date, then try again.

**Comment by donvdp** [comment] 2021-08-16 22:28
The servers that i have running on java 14 are not using nashornplus. And my 1 server that is running java 16 has the nashornplus plugin version 1.10 (latest) installed and is running.

**Comment by donvdp** [comment] 2021-08-18 15:10
Hi There ElBananaa, i have been messing arround your example and i got it working, but there seems to be some issues when i am online myself.

On discord my username is donvdp. 
Minecraft ingame my username is donvdp.

I have a second account called Donssie

When i have donssie in the lobby server and donvdp and send a message from discord to minecraft.

donvdp in the prison server sees:
![image](https://user-images.githubusercontent.com/10013800/129923136-245cd76f-e21c-4497-8841-ab30de712a93.png)

donssie in the lobby server sees:
![image](https://user-images.githubusercontent.com/10013800/129923151-167109c6-9848-439c-b607-2abec6428577.png)

So it seems to be that because i am online the chat is formatted differently ?

Note that it is not only for me, when i have both players "donnie" and "donvdp" in the prison server and send a message from discord to minecraft 

Donssie sees:
![image](https://user-images.githubusercontent.com/10013800/129923452-3064a499-8c24-47a4-a253-a5ae6288940c.png)

donvdp sees:
![image](https://user-images.githubusercontent.com/10013800/129923566-3bbb4706-b79f-44a3-b83d-dc0c42884247.png)

**Comment by kangarko** [comment] 2021-08-20 17:52
I sorted out the {sender_is_discord} not properly working issue, please correct me when I missed something: https://www.loom.com/share/0137bb5a4c6045ad806635d6d9e20419

Also next version will add a forwarding key to prevent duplication, please read its changelog and then reply to your appropriate ticket since I remember you having another one for duplicated messages.

Closing it good faith this is now resolved, comment below if you need any help and I am happy to do so!

**Closed as completed by kangarko** 2021-08-20 17:52 UTC
