### ISSUE TITLE
1.16.5: ~not working in /nick

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1235] opened 2021-08-15 00:29 UTC
Hi there, ive been testing arround and it seems that the "~" is not working for people that are having a nickname.

I am running EssentialsX and when i turn off ChatControlRed the ~ is working just fine, as seen below
![image](https://user-images.githubusercontent.com/10013800/129463268-790033f7-2ae5-4271-8aad-3342280a84d3.png)

When i have ChatControlRed turned on i dont get the "~" anymore. as seen in screenshot below:
![image](https://user-images.githubusercontent.com/10013800/129463362-a0c66c51-3bf1-45a8-890a-64aa8d6e08c5.png)

I have been messing arround with the ChatControlRed config file and i have added the " ~ " in the "tag" section of the config file. But even after this tweak there is no joy. But i dont think the tag section applies to the nickname "~" issue, since it uses an vault placeholder.

chat.yml that i am using to format the chat
![image](https://user-images.githubusercontent.com/10013800/129463316-2942ab19-88fb-4d3d-8dde-f13e59b81c97.png)

I have tried to ingame parse a few placeholders to see if the prefix " ~ " is out there somewhere, but no joy.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

![image](https://user-images.githubusercontent.com/10013800/129463307-afb91aea-aaf7-4c9c-a2c0-8c21eba8b3ab.png)

essentials config with "~" enabled
![image](https://user-images.githubusercontent.com/10013800/129463329-14b68508-ec9f-4e8c-b8c7-627c59e23de6.png)

**Comment by ElBananaa** [comment] 2021-08-15 00:40
Hey!
Your tag part isn't configured correctly. Basically, it looks like it isn't even enabled right now. As you can see on your screenshot, there is:
`Apply_On: []`. Try with `Apply_On: [nick]` and it should fix your issue.

**Comment by donvdp** [comment] 2021-08-15 10:25
Hey there ElBananaa,

As i understand, changing the config with "Apply_On [nick]" will turn on this 'tag' function. But i do not want to do this. Because I am using EssentialsX for the /nick formatting. 
![image](https://user-images.githubusercontent.com/10013800/129475295-5a3f3ae6-4d48-422e-937d-faa278fb7b6e.png)

So as stated in the ChatControlRed settings.yml file i need to leave this "Apply_On: []" just the way it is right ? Since im using EssentialsX for formatting the nickname.

just for sake i have tested what you suggested ElBananaa and with ingame command "/tag nick <nickname>" it will work. But the /tag nick command is new to my palyers and i dont want a complicated command like this. using the /tag funtion wouldnt be a problem if the command would just be /nick. and if the ingame return command wouldnt be so funcky
![image](https://user-images.githubusercontent.com/10013800/129475521-973f25fb-1662-483d-8521-10f346d792e8.png)

so i'dd rather just stick to EssentialsX for formatting my player's nickname ingame, but i do need the  " ~ " to work

**Comment by ElBananaa** [comment] 2021-08-15 14:11
> Hey there ElBananaa,
> 
> As i understand, changing the config with "Apply_On [nick]" will turn on this 'tag' function. But i do not want to do this. Because I am using EssentialsX for the /nick formatting.
> ![image](https://user-images.githubusercontent.com/10013800/129475295-5a3f3ae6-4d48-422e-937d-faa278fb7b6e.png)
> 
> So as stated in the ChatControlRed settings.yml file i need to leave this "Apply_On: []" just the way it is right ? Since im using EssentialsX for formatting the nickname.
> 
> just for sake i have tested what you suggested ElBananaa and with ingame command "/tag nick " it will work. But the /tag nick command is new to my palyers and i dont want a complicated command like this. using the /tag funtion wouldnt be a problem if the command would just be /nick. and if the ingame return command wouldnt be so funcky
> ![image](https://user-images.githubusercontent.com/10013800/129475521-973f25fb-1662-483d-8521-10f346d792e8.png)
> 
> so i'dd rather just stick to EssentialsX for formatting my player's nickname ingame, but i do need the " ~ " to work

Hey,
Alright, I understand.
You can create an alias for the /chc tag nick command so you only need to use /nick instead if you want too.
Anyways, since you want to use essentials as your nick plugin. As said in one of your other tickets, try to remove essentialsxchat, and let us know if it helps here too

**Comment by donvdp** [comment] 2021-08-16 06:47
Hi there ElBananaa, i do NOT want to remove EssentialsXChat. its been working fine in the past and this missing " ~ " is just because there is a bug in the ChatControlRed plugin. Can you just fix the bug in stead of forcing me to change stuff in my server?

I ofcourse am willing to test something for you, not that i get compensated for it. im not a beta tester or anything.....

Removing the EssentialsChat does NOT fix this. Nor would i want it to be the fix, just fix the damn bug thats causing it?

**Comment by ElBananaa** [comment] 2021-08-16 15:56
Hey, alright,
After testing this by myself on an 1.16.5 fresh install, I can confirm the issue happens with and without EssentialsXChat. No matter the placeholder used in the format chat, or the prefix specified in EssentialsX config file, it simply isn't there.

To bo clear, I understand that you're being upset, but you don't find the cause of a bug and its fixes by simply snapping fingers. However, I never forced you to change stuff on your server, and I'l never force anyone to do anything they don't want to do. I asked you to try a few things. If you don't want to try them, then simply don't. ^^
Finally, of course, you're not a beta tester, and I'm grateful that you accepted to try the few things I asked. I'm sorry if this bothers your, but since I'm unable to reproduce the exact same setup than yours, this is the best way to find the cause of the issue and/or a fix.

However, being upset doesn't give you any rights of being rude/agressive towards anybody here. Writing "just fix the damn bug" is pointless here. I've been polite and friendly with you on all your tickets until now, I always tried to answer as fast and as efficient as possible, the only thing I ask back, is to be polite, and patient.
Finally, I am not the plugin developer, but only a support member, so, unfortunately, I cannot fix this issue.

As for now, there's nothing else I can do about this issue, so please wait for Kangarko to review it.
Have a nice day.

**Comment by donvdp** [comment] 2021-08-17 10:31
Hi ElBananaa, I don’t understand what is wrong? i am not trying to be rude or aggressive, I think I made a grammar error :(
"Just fix the damn bug" is **_not_** meant as a remark on your inactivity or inability to resolve the issue, it is meant as a way that 'a' bug is nasty. sorry I didn’t mean offence. English is not my first language and I think I simply made an error in getting me message across :( No offence meant in any case. I hope I typed that correctly haha

To be clear, it is frustrating that the setup of ChatControlRed is taking more than 2 weeks now, but that’s just something that i take for granted, because the features that ChatControlRed is offering are pretty neat :-)

So far, I have tested everything you suggested and I believe that I am cooperating in an attempt to find the solution and ultimately making this plugin more stable / easier to setup :-)  

in my previous message I wrote that Removing the EssentialsChatX has not fixed the problem and the " ~ " still is not working. from what I understand we are going to wait for Kangarko to read this ticket and see what he makes of this?

Perhaps there is something that I can do in the meantime. You were not able to reproduce the results in your test setup. perhaps you could share your files from your setup with me? maybe I can deduce some differences with my setup that may lead me to a possible error in my setup.

**Comment by ElBananaa** [comment] 2021-08-17 16:08
> Hi ElBananaa, I don’t understand what is wrong? i am not trying to be rude or aggressive, I think I made a grammar error :(
> "Just fix the damn bug" is **_not_** meant as a remark on your inactivity or inability to resolve the issue, it is meant as a way that 'a' bug is nasty. sorry I didn’t mean offence. English is not my first language and I think I simply made an error in getting me message across :( No offence meant in any case. I hope I typed that correctly haha
> 
> To be clear, it is frustrating that the setup of ChatControlRed is taking more than 2 weeks now, but that’s just something that i take for granted, because the features that ChatControlRed is offering are pretty neat :-)
> 
> So far, I have tested everything you suggested and I believe that I am cooperating in an attempt to find the solution and ultimately making this plugin more stable / easier to setup :-)
> 
> in my previous message I wrote that Removing the EssentialsChatX has not fixed the problem and the " ~ " still is not working. from what I understand we are going to wait for Kangarko to read this ticket and see what he makes of this?
> 
> Perhaps there is something that I can do in the meantime. You were not able to reproduce the results in your test setup. perhaps you could share your files from your setup with me? maybe I can deduce some differences with my setup that may lead me to a possible error in my setup.

Hey,
As I said, I completely understand the fact that you're annoyed, however, the fact that you wrote "just fix the damn bug" sounded like you lost patience, and was starting to be aggressive. If this wasn't the case, then there's no need to apologize about anything ;)
As I said, I'm here to help, and I'm glad to help anybody.

A few people already reported that the plugin is hard to setup. So I already asked Kangarko about adding a "Tips & Tricks" channel on the discord where some users and I would be able to post some working examples, setup tutorials and things like that, that we can easily update. Let's just hope he likes the idea ^^

Also, as I said in my previous message, I was able to reproduce this issue with and without EssentialsXChat that's why I said the only thing I can suggest as for now is to wait for Kangarko (which, I hope, shouldn't take more than a few days) to review your issue. So far, I don't remember anyone reporting a similar issue, so unfortunately, I don't have any other suggestions to fix this.

**Comment by kangarko** [comment] 2021-08-20 12:59
> Hi there, ive been testing arround and it seems that the "~" is not working for people that are having a nickname.
> 
> I am running EssentialsX and when i turn off ChatControlRed the ~ is working just fine, as seen below
> ![image](https://user-images.githubusercontent.com/10013800/129463268-790033f7-2ae5-4271-8aad-3342280a84d3.png)
> 
> When i have ChatControlRed turned on i dont get the "~" anymore. as seen in screenshot below:
> ![image](https://user-images.githubusercontent.com/10013800/129463362-a0c66c51-3bf1-45a8-890a-64aa8d6e08c5.png)
> 
> I have been messing arround with the ChatControlRed config file and i have added the " ~ " in the "tag" section of the config file. But even after this tweak there is no joy. But i dont think the tag section applies to the nickname "~" issue, since it uses an vault placeholder.
> 
> chat.yml that i am using to format the chat
> ![image](https://user-images.githubusercontent.com/10013800/129463316-2942ab19-88fb-4d3d-8dde-f13e59b81c97.png)
> 
> I have tried to ingame parse a few placeholders to see if the prefix " ~ " is out there somewhere, but no joy.
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> ![image](https://user-images.githubusercontent.com/10013800/129463307-afb91aea-aaf7-4c9c-a2c0-8c21eba8b3ab.png)
> 
> essentials config with "~" enabled
> ![image](https://user-images.githubusercontent.com/10013800/129463329-14b68508-ec9f-4e8c-b8c7-627c59e23de6.png)

Hey there!

I apologies for a late reply. The problem is that when I am asking Essentials for a player's nick, their API returns the nick without that prefix.

So I just made a simple code change that'll include our own Tag.Nick_Prefix from settings.yml in front of player nick names!

![a](https://i.imgur.com/ZUulcn5.png)

PS: Should you wish to use our own nick feature, and you want to type /nick instead of "/tag nick" to invoke this command, see rules/command.rs file, line 85 by default, and comment the two command rules for this alias.

PPS: I was not able to reproduce that funky message with ")? etc. :( (https://i.imgur.com/NMiQBN3.png), you can try resetting the Commands.Tag.Success_V2 key in your localization/messages_x.yml file which you use.

**Comment by kangarko** [comment] 2021-08-20 13:01
Also I apology you had a poor customer support experience here. I am the only developer of the plugin so if anything you will need for me to get back directly so I can make code changes and push new releases asap. That typically happens 1-2 weekly.


> However, being upset doesn't give you any rights of being rude/agressive towards anybody here. Writing "just fix the damn bug" is pointless here. I've been polite and friendly with you on all your tickets until now, I always tried to answer as fast and as efficient as possible, the only thing I ask back, is to be polite, and patient.
> Finally, I am not the plugin developer, but only a support member, so, unfortunately, I cannot fix this issue.

@ElBananaa please disregard teaching people morals or ethics since that is not the way to go about giving support, right or not, I am not a moral judge. I appreciate the help you are giving since the beginning of this year, if you are unsure then just leave the ticket hanging until I come back, I do not wish to engage in personal discussions like this since it is just a bad experience for both of you

**Comment by kangarko** [comment] 2021-08-20 13:03
Closing this since thanks to the code edit change I made. 

Just to summarize, the next version will be pushed out today and you will be able to append a prefix to nicks while using EssentialsChat and Essentials' nicks' solution with putting ~ into our Tag.Nick_Prefix key in settings.yml

**Closed as completed by kangarko** 2021-08-20 13:03 UTC

**Comment by donvdp** [comment] 2021-08-20 15:52
Thanks !

**Comment by donvdp** [comment] 2021-08-22 23:48
So, It does sorta work, but its not completely nice yet.
I have decided to use as little EssentialsX as I can, so I am trying to switch over to chatcontrolred, here is what I did:

1) remove the EssentialsXChat from the server
2) reconfig EssentialsX config.yml to disable the /nick command.
![image](https://user-images.githubusercontent.com/10013800/130372795-f379fe00-a2dc-45b7-8a19-3cefb3ec71fc.png)

3) ChatcontrolRed settings.yml --> Tag.Apply_On: [nick]
4) ChatcontrolRed settings.yml --> Tag.Nick_Prefix: '~'
5) ChatControlRed/formats/chat.yml --> edit the part of the nickname to use placeholder {nick}

6) ChatcontrolRed rules/command.rs file --> remove comment for rules with /nick command. (lines 90 to 94 and 98 to 101)
7) ChatcontrolRed rules/command.rs file --> change permission node to match the chatcontrol.command.tag.nick perm node.

8) Save all changes and reboot server.

When i do all this, I can change my ingame nick succesfully. When i have a custom nick there is a " ~ " in front of my name so that works perfectly !

However: I still have 2 questions/problems:

1) How can my admins change a nickname from another player? because if a player for example uses a bad word we want to be able to correct there nickname. i couldnt find a perm node or anything for something like: "chatcontrol.command.tag.nick.other"

i did find a permission node called "chatcontrol.command.tag.admin""but granting that to my admins did not result in them being able to change the nicknames of other players. (with command /tag nick <otherplayername> <newnick/off>

2) When i for example execute command "/nick test" I get a weird ingame message:
![image](https://user-images.githubusercontent.com/10013800/130373280-453f0fdd-3189-4af9-a2ec-3fa2495a6493.png)

Is there a way for me to dress this message up and format this in a way?

**Comment by ElBananaa** [comment] 2021-08-23 00:04
Hey!

- Regarding your first question, I believe the permission to edit other players' nicks is `chatcontrol.command.tag.admin`.
To edit users' nicks, your staff members will need the `chatcontrol.command.tag.admin` permission, then will need to run `/chc tag nick <playerNick> <newPlayerNick/off>` to either edit their nick, or disabling it.
If you wish, you should still be able to create another custom command using the rules system.

- Regarding your 2nd issue, I'm unable to reproduce it on my side. Could you please try to delete the lang file and restart the server? Also make sure NashornPlus is installed. ^^

**EDIT: It's also important to know that our internal nick system works with the rules system. So if one of your players try to use a nick that matches any of your rules, it won't work** ^^

**Comment by donvdp** [comment] 2021-08-23 00:14
With the perm node "chatcontrol.command.tag.admin" granted to my admins they were able to use the comman "/chc tag nick <playerNick> <newPlayerNick/off>" succesfully! thanks :-) I will create a nice alias in the command.rs file later in order to make it pretty for my admins.

regarding the 2nd issue:
NashornPlus 1.10 is already installed. i have deleted the lang files inside the "localization" folder and rebooted the server. when booting up i see a few errors:
![image](https://user-images.githubusercontent.com/10013800/130374709-4b376cd3-7da3-445a-a55b-3f0ac3347f5a.png)
though it reports to be running NashornPlus when the server is booted up and running:
![image](https://user-images.githubusercontent.com/10013800/130374735-cf52ba08-6958-4769-b614-e35e6cc5dd6b.png)
I am running NashornPlus v1.1.0
![image](https://user-images.githubusercontent.com/10013800/130374749-090e6747-3b65-4c3c-aaf2-acb9097cfdd0.png)



also when changing a nickname ingame i get a console output that says no java is loaded:
![image](https://user-images.githubusercontent.com/10013800/130374671-e9cfb274-9c9e-41c7-9baa-bada435078e5.png)

This seems to be related to my previous ticket #1225

Though i am already running Featherboard v5.0.3, i dont know what to do next. I seem to be stuck :P
![image](https://user-images.githubusercontent.com/10013800/130374909-7f94d5b5-379f-4b1a-a5b4-b78ce3ea24fc.png)

**Comment by ElBananaa** [comment] 2021-08-23 00:29
Oh, yeah, I forgot this issue. I'm not sure to understand why this error appears on your side since it doesn't on mine. The only thing that comes to me right now is the usage of MVDWPlaceholderAPI. You can remove it from your server if you use FeatherBoard v5.X since it's not needed anymore (cf. Featherboard v5.0.0a changelog). Hopefully it'll fix the issue.

Anyways, from what Kangarko said on another issue (cf. #1256), the next version should get rid of NashornPlus, which will be replaced by an external library provided by spigot, and it should also help, if what I suggested above doesn't work.

**Comment by donvdp** [comment] 2021-08-23 00:30
going to test this right now

was indeed using MVdWPlaceholderAPI
![image](https://user-images.githubusercontent.com/10013800/130375404-f24b0560-aede-44b7-9643-eb8ac8711f3e.png)

Disabled. server rebooting

still showing boot up errors:

![image](https://user-images.githubusercontent.com/10013800/130375467-50b15d22-dbb1-4ffd-a647-a83cb08fdef6.png)


testing if ingame messages persists

negative, still having this:

![image](https://user-images.githubusercontent.com/10013800/130375532-99e28ce6-0474-4a77-aacc-d242131d6889.png)


ill be patiently awaiting the next version, for now ill stick with the essentialsX nick command.

**Comment by ElBananaa** [comment] 2021-08-23 00:41
Hmm 🤔
I don't see a lot of other options here 😕

The issue is definitely caused by the fact that, for some reason, NashornPlus is disabled. However, I don't know if it's related to another plugin, or to your java version, or to anything else (such as your distro, your server software or anything else, who know...)

Anyways, yes, i'd suggest sticking with EssentialsX nick system for now.
Thanks for your patience! 😉

**Comment by kangarko** [comment] 2021-08-23 16:53
Thanks to the tip from Maxim, the developer of Featherboard, and the recent updates of SpigotAPI, I was able to drop NashornPlus dependency completely for MC 1.16+. Just use the next version (although marked BETA) and remove NashornPlus.

**Comment by donvdp** [comment] 2021-08-24 07:35
i can confirm that i no longer need NashornPlus in order to run the plugin. Everything seems to be working fine now !
