### ISSUE TITLE
1.21: VelocityControl 1.0.8 stops functioning after bcreload

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#2740] opened 2024-07-04 02:43 UTC
### Information about the issue/bug

**Affected versions:** at least 1.0.7 + 1.0.8 (did not try earlier)

We have been troubleshooting some issues with the latest VelocityControl and noticed that when we do a `bcreload` (even without changing the config) it seems to break all chat and messaging. Only a Velocity restart seems to resolve it.

With debugging enabled, I can see this message normally:
```
[com.velocitypowered.proxy.console.VelocityConsole]: [bungee] Incoming packet CHANNEL from <server>
```
But when I do a bcreload and change nothing else, I no longer see this message and cross-server chat doesn't work.

**Comment by kangarko** [comment] 2024-07-04 07:36
Thanks, will be fixed.

**Closed as completed by kangarko** 2024-07-04 07:36 UTC
Labels: velocity

**Comment by addstar** [comment] 2024-07-04 08:30
Thanks also for this fast fix! :100:

**Comment by kangarko** [comment] 2024-07-04 08:45
If you enjoyed and hopefully it will work as intended, give it a nice review at builtbybit please :)
