### ISSUE TITLE
1.19.2: db file blows up from time to time

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#2064] opened 2022-08-14 15:03 UTC
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/cc68aa92bb754fa5a62e28aff21d26f9

### Information about the issue/bug

Sometimes CCR blows up on player messages and plugin is unusable while spams into console on player messages. Are you sure you use locks/synchronization for your "async" file writes/reads of the db file?

**Comment by ElBananaa** [comment] 2022-08-14 16:07
I think getting rid of the current flatfile database and replacing it with a true H2/SQLite database would be a great improvement and a potential fix to these issues that have been happening ever since the plugin was released.

**Comment by kangarko** [comment] 2022-08-15 15:22
Thank you, should be resolved in the next version.

**Comment by kangarko** [comment] 2022-08-15 15:22
Next time if it happens please also include your data.db so I can have a look at the structure.

**Closed as completed by kangarko** 2022-08-15 15:22 UTC

**Comment by radiant-ai** [comment] 2022-08-15 15:27
Sorry, the file would be irrelevant because it gets fixed after some time
and all these "outages" happen during my sleep or when I am bussy. They get
fixed by themselves randomly (most likely on some player relog).

**Comment by ElBananaa** [comment] 2022-08-15 15:38
@kangarko Can confirm this happened to me 2 or 3 times randomly yesterday on my own local test server. I never had this issue before (tho I pretty much never used a flatfile database), but yeah, it was completely random. I looked at the data file when it happened, and the file was perfectly fine.

**Comment by kangarko** [comment] 2022-08-15 17:40
Must have been caused by https://github.com/kangarko/Foundation/commit/2c3fc22b4f631c8a3d64bba5fb4401bc00788d3d, I have reversed it now.

**Comment by radiant-ai** [comment] 2022-08-15 18:17
You can let it be async just use synchronized blocks or locks or single
tread executors for all IO.
