### ISSUE TITLE
Disable case sensitivity at ignore-string

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#90] opened 2016-03-31 07:13 UTC
Hey there,

I recently noticed that someone tried to write an url in the chat that has been whitelisted and triggered the advertisement rule anyways. After a while I realized that he wrote the first character of the url in upper case which seemed to be the cause for this.

So here my question: Is there a way to disable the case sensitivity for ignored strings (at all through all config files)?

For further details about the rule itself as well as the handler, take a look here: https://github.com/kangarko/ChatControl/issues/88

**Comment by Abadao** [comment] 2016-04-02 04:10
Take a look on rules.txt. 

match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me|io|onion)\b

Remove A-Z Maybe?

Can you show up you whitelist of websites? maybe I can help.

**Comment by kangarko** [comment] 2016-04-02 16:22
Cannot reproduce.

Tested:
www.google.de -> allowed
www.Google.De -> also allowed

**Comment by Abadao** [comment] 2016-04-02 17:39
I have the same problem here, i think its my config

match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me|io|onion|de)\b
# If you want to whitelist your server, it is only necessary to add it once in format:
# website.domain (example: procraft.com)
# To add more domains simply add them after the last one and divide by |
ignore string minecraft:|youtube.com|imgur.com


tested:
www.youtube.com -> allowed
www.YouTube.com -> allowed
youtube.com -> allowed
YouTube.com ->  disallowed

**Comment by kangarko** [comment] 2016-04-30 08:50
Fixed in 5.3.2

**Closed by kangarko** 2016-04-30 08:50 UTC
Labels: question
