### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by NebulusFR** [kangarko/ChatControl#2244] opened 2022-12-30 22:38 UTC
### "/version ChatControlRed" - plugin version

Latest

### Are you using MySQL?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/277398aea2cd4affab08c6db8e399b99

### "/chc debug" output (strongly recommended)

/

### Information about the issue/bug

Error, message of join send two times

**Comment by james090500** [comment] 2022-12-30 23:12
This looks like you're using a dev version, please make sure you're using 3.11.0.

https://github.com/kangarko/VelocityControl/releases/tag/3.11.0

**Comment by NebulusFR** [comment] 2022-12-31 02:11
![image](https://user-images.githubusercontent.com/36241286/210121985-f29b7ecc-8473-45f0-b71e-7ef3fcab0941.png)

**Comment by kangarko** [comment] 2023-01-03 16:28
@james090500

**Comment by NebulusFR** [comment] 2023-01-03 17:04
I believe another problem has just arisen. Since I updated to this new version. My Velocity crashes every X times and becomes unresponsive

**Comment by kangarko** [comment] 2023-01-03 18:32
Can you provide some crash reports for James to reproduce?

**Comment by NebulusFR** [comment] 2023-01-03 18:33
I have nothing because my Velocity (proxy) just freeze. For it to work again, I have to restart it

**Comment by kangarko** [comment] 2023-01-04 09:58
Hopefully James will get back to you shortly, thank you for your patience.

**Comment by NebulusFR** [comment] 2023-01-04 11:38
Alright, I'll wait

**Comment by james090500** [comment] 2023-01-04 15:11
Hi,

Can you send your join message file.

**Comment by NebulusFR** [comment] 2023-01-04 15:30
Hi,

```
group default
prefix &a+&2・
message:
- &a{player}
```

**Comment by NebulusFR** [comment] 2023-01-04 15:31
I have the impression that it is fixed since the new version 10.16.2
But, i'm not sure

**Comment by NebulusFR** [comment] 2023-01-05 10:29
Error is here again

```
------------------------------------[ 05.01.2023 11:25:35 ]-----------------------------------
VelocityControl encountered an IndexOutOfBoundsException
Running Velocity ProxyVersion{name='Velocity', vendor='Velocity Contributors', version='3.2.0-SNAPSHOT (git-697d08ba-b216)'} and Java 17.0.4.1
----------------------------------------------------------------------------------------------

More Information: 
Error parsing rule: Player Message {
	'Type' = 'join'
}
IndexOutOfBoundsException Index 1 out of bounds for length 1
	 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	 at java.base/java.util.Objects.checkIndex(Objects.java:359)
	 at java.base/java.util.ArrayList.get(ArrayList.java:427)
	 at org.mineacademy.velocitycontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:157)
	 at org.mineacademy.velocitycontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:457)
	 at org.mineacademy.velocitycontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:360)
	 at org.mineacademy.velocitycontrol.operator.Operator$OperatorCheck.start(Operator.java:426)
	 at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:236)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	 at java.base/java.lang.Thread.run(Thread.java:833)
----------------------------------------------------------------------------------------------
```

**Comment by james090500** [comment] 2023-01-07 15:37
Can you test this (Very debug code)
https://github.com/kangarko/VelocityControl/suites/10182460501/artifacts/498156378

**Comment by NebulusFR** [comment] 2023-01-09 13:06
I will test, thank you. Afterwards, the error hardly happened anymore. Compared to the previous version, your version is almost twice as light

**Comment by NebulusFR** [comment] 2023-01-10 10:08
Error when i'm updating VelocityControl

```
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]: [VelocityControl] !-----------------------------------------------------!
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]: [VelocityControl] ERROR: JavaScript placeholders will not function!
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]:   
[11:06:45] [Velocity Async Event Executor - #0/INFO] [warpsystem]: Status:
[11:06:45] [Velocity Async Event Executor - #0/INFO] [warpsystem]:  
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]: [VelocityControl] Your Java version/distribution lacks the
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]: [VelocityControl] Nashorn library for JavaScript placeholders.
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]:   
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]: [VelocityControl] To fix this, install the NashornPlus
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]: [VelocityControl] plugin from mineacademy.org/nashorn
[11:06:45] [Velocity Task Scheduler - #0/ERROR] [velocitycontrol]: [VelocityControl] !-----------------------------------------------------!
```

**Comment by NebulusFR** [comment] 2023-01-10 14:59
And i have another error with ChatControl-Red

```
[10Jan2023 15:58:01.913] [Craft Scheduler Thread - 14/INFO] [STDERR/]: [org.mineacademy.chatcontrol.model.Discord:lambda$sendChannelMessageDelayed$1:309]: java.lang.NullPointerException
[10Jan2023 15:58:01.913] [Craft Scheduler Thread - 14/INFO] [STDERR/]: [org.mineacademy.chatcontrol.model.Discord:lambda$sendChannelMessageDelayed$1:309]: 	at org.mineacademy.chatcontrol.model.Discord.lambda$sendChannelMessageDelayed$1(Discord.java:259)
[10Jan2023 15:58:01.913] [Craft Scheduler Thread - 14/INFO] [STDERR/]: [org.mineacademy.chatcontrol.model.Discord:lambda$sendChannelMessageDelayed$1:309]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[10Jan2023 15:58:01.913] [Craft Scheduler Thread - 14/INFO] [STDERR/]: [org.mineacademy.chatcontrol.model.Discord:lambda$sendChannelMessageDelayed$1:309]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[10Jan2023 15:58:01.913] [Craft Scheduler Thread - 14/INFO] [STDERR/]: [org.mineacademy.chatcontrol.model.Discord:lambda$sendChannelMessageDelayed$1:309]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[10Jan2023 15:58:01.913] [Craft Scheduler Thread - 14/INFO] [STDERR/]: [org.mineacademy.chatcontrol.model.Discord:lambda$sendChannelMessageDelayed$1:309]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[10Jan2023 15:58:01.913] [Craft Scheduler Thread - 14/INFO] [STDERR/]: [org.mineacademy.chatcontrol.model.Discord:lambda$sendChannelMessageDelayed$1:309]: 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kangarko** [comment] 2023-01-31 09:12
Sorry that nobody got back to you; this error is on my end, I believe it was solved in the last version so I am closing this in good faith. Let me know if you still will experience anything suspicious. Thank you.

**Closed as completed by kangarko** 2023-01-31 09:12 UTC
Labels: velocity
