### ISSUE TITLE
{prefix_warn} Improvements!

### ISSUE THREAD

**Issue by MuriloWentz** [kangarko/ChatControl#1892] opened 2022-05-13 23:55 UTC
Hey, if you add an {prefix_warn} or any {prefix_xxxx} in front of a message that already has a prefix by default, it just gets added to the message. I didnt find a way to remove the prefix a message has attached to it. if theres a way, let me know. Otherwise my suggestion would be making the prefix of the message be overriden by the {prefix_warn} the player adds and so..

1. How it would benefit others? 

 Well, some messages would be great to be able to change the prefix to any other you want

3. What would happen if we won't implement this feature? How's your server being affected? 
 
 Im creating a toggle menu, and the messages are all ''warn" prefixed, and im not being able to change the chc prefixes to my liking

**Comment by TheIntolerant** [comment] 2022-05-15 08:25
Dupe of #1448

I unfortunately haven't had time to sit down and go thru all of these messages and add the prefixes in the each line to help and improve this, so the changes made there are currently the only way to achieve this

---

however, I've made a Pull request, so people know that adding ``@noprefix`` removes any hardcoded prefix in a messsage, which allows you to completely edit the message.

For example, I can change the prefix by doing something like this
![image](https://user-images.githubusercontent.com/48093184/168463758-31a11ae4-35e8-41ab-b514-79d6f21b8cc1.png)

**Comment by TheIntolerant** [comment] 2022-05-15 08:26
I will leave this open so the dev can decide if they wish to change this or leave it as it is for now.

**Comment by MuriloWentz** [comment] 2022-05-16 02:43
Thanks bro, that should be fine for me, but i would be more quality-looking if the prefix could be overriden automatically

**Comment by kangarko** [comment] 2022-05-16 14:07
Thanks, the easiest way is to:

1 Either use {prefix_X} and then customize its look in the Prefix section of messages_X.yml file in localization, or

2. Simply not place anything before your message, set the Prefix in the above section to "" and then you can simply manually place prefixes such as:

No_Console: "[!] You may only use this command as player!"

Let me know if I misunderstood something or you need more clarification. Thanks to @TheIntolerant for the help!

**Closed as completed by kangarko** 2022-05-16 14:07 UTC
