### ISSUE TITLE
[1.19] [10.12.10] Links not clickable

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2048] opened 2022-08-06 14:27 UTC
### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

It is impossible to click on some links. Links like `https://google.com` or `rgb.birdflop.com` work, but some links (such as the screenshot) just do not. It is mostly links that include `/` after the domain.

![image](https://user-images.githubusercontent.com/87967222/183253008-2c29db05-34d8-4dbe-ae16-d3784969c64a.png)

**Comment by ElBananaa** [comment] 2022-08-06 14:36
Dupe of #2041

**Closed as completed by ElBananaa** 2022-08-06 14:36 UTC
