### ISSUE TITLE
1.21.1: Boolean return?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2915] opened 2024-12-21 17:41 UTC
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.3

### Steps to reproduce

Hello, I have code like this:
```yml
Type: FORMAT
Key: "pack_check"
Value: |-
    checkPack();
    
    function checkPack() {
        var val = "{some_palceholdeer}";
        if (val == "some_reply") {
            return true;
        } else {
            return false;
        }
    }
  
Sender_Condition: ""
Sender_Permission: ""
```

and I use it in chat format:
```yml

**Comment by kangarko** [comment] 2024-12-23 17:41
Duplicate of your other ticket, lets continue there.

**Closed as completed by kangarko** 2024-12-23 17:41 UTC
