### ISSUE TITLE
Towny and ChatControl dont work with deluxechat

### ISSUE THREAD

**Issue by jordanwilliams1** [kangarko/ChatControl#207] opened 2017-05-06 09:32 UTC
can you fix the compatibility of this plugin with deluxechat and towny? When I use deluxechat and towny hook is set to true ChatContolr doesn't work and allows people to swear. 

Here is my config for deluxechat:
https://hastebin.com/visufutere.php

**Comment by kangarko** [comment] 2017-05-08 07:29
I cannot reproduce:

![pic](https://i.imgur.com/lMovwAO.png)

Please make sure you have chat formatter disabled in ChatControl (Chat.Formatter), since you're using one from DeluxeChat. When it does not work? Never or only in certain scenario?

**Comment by jordanwilliams1** [comment] 2017-05-09 17:53
It never works. It only works if i disable the towny hook in the channel.yml in towny. But if i do that then it causes issues with bungee cross server chat.

I've just created a test server for you with my configs.
https://mega.nz/#!A1wkiLzQ!uWNPHxHXjVD_KUP1pJFnYHxipuPQqfaMbldbGUFOwDo

This might be something I've miss configured but I'm not sure.
<img>https://i.gyazo.com/141bac8398014f1068e0a84952405274.png<img/>

Thanks for replying to my post.

**Comment by jordanwilliams1** [comment] 2017-05-11 13:28
@kangarko Did you get a chance to look at this? ChatContol only doesn't work when the towny hook is true in the channels.yml

**Comment by kangarko** [comment] 2017-05-11 20:21
Hey, I didn't get to test out because of exams. If the towny hook makes it work/not work, it seems like a priority issue (the Pro version has the ability of configuring [event priorities](https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities) in itself). I will try to backport it to the free version once back at workspace.

**Comment by jordanwilliams1** [comment] 2017-05-11 21:07
Thank you :)

**Comment by kangarko** [comment] 2017-05-13 13:50
I have pushed a new release, plesae

**Comment by jordanwilliams1** [comment] 2017-05-14 09:42
@kangarko That didn't work :(

**Comment by kangarko** [comment] 2017-05-14 18:32
Try setting Checker to LOWEST, to HIGHEST or even to MONITOR. Please restart the server after each change.

**Comment by jordanwilliams1** [comment] 2017-05-14 18:32
I Tried HIGHEST and MONITOR and it didn't work :(

**Comment by kangarko** [comment] 2017-05-14 18:33
What about LOWEST?

**Comment by jordanwilliams1** [comment] 2017-05-14 18:35
O That worked :)

**Comment by kangarko** [comment] 2017-05-14 18:53
Closing :)

**Closed by kangarko** 2017-05-14 18:53 UTC
Labels: issue

**Comment by axemwa** [comment] 2018-07-15 05:47
Works for me too but causes the message to be sent in general chat aswell as town chat so 2 messages are sent, know a fix for this?

**Comment by axemwa** [comment] 2018-07-15 06:55
nvm using channels.yml instead fixed it
