### ISSUE TITLE
Velocity: Error loading users.json

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl#2430] opened 2023-08-18 12:34 UTC
### "/version ChatControlRed" - plugin version

N/A

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

@james090500 please fix this first launch error:

![a](https://i.imgur.com/697AlbE.png)

Happens when no plugin data folder exists

**Comment by kangarko** [comment] 2023-08-18 12:37
@james090500 and this issue:

![a](https://i.imgur.com/0A19om4.png)

**Comment by james090500** [comment] 2023-08-18 12:42
Will look into these. The first error will resolve automatically on a reboot but will fix it

Second one I haven't seen before but will look

**Comment by kangarko** [comment] 2023-08-18 12:44
Thanks, but it's an inconvenience for the user having to read the error on the first launch. Would be great to fix this.

The second happens when I force close my Spigot server.

**Comment by james090500** [comment] 2023-08-18 13:28
Yeh no worries at all. I didn't realise it was there!

Also thanks for replication steps!

**Comment by james090500** [comment] 2023-08-23 10:44
Ok the second error was caused by the first. This is fixed with 3.11.6

**Closed as completed** 2023-08-23 10:54 UTC
Labels: velocity

**Comment by kangarko** [comment] 2023-08-23 13:37
Many thanks James!
