### ISSUE TITLE
1.16.5 : Questions & Tab-Completion Suggestion

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl#1178] opened 2021-07-25 03:02 UTC
¡Hey there, great plugin!

I was wondering how to do this:
I have differents skyblock servers but all the chat is sync, right?
If i want to do that for some survivals, and the chat to be sync BUT only tab-complete /msg for those in the skyblock server/survival server its possible? So it doesnt mix  players. Should i uso a different mysql for the survivald and skyblocks? 

Thanks and sorry for my spelling.

**Comment by msmanui** [comment] 2021-07-25 03:18
Also for example:
```
    Rank_1:
      Message: "&c[Admin] "
      Sender_Permission: "my.rank.admin"
    Rank_2: 
      Message: "&9[Mod] "
      Sender_Permission: "my.rank.mod"
    The_Rest: 
      Message: "&7{pl_prefix+}{player}&7: &f{message}"
```

Its possible to add priorities? Because for example, if a vip has purchased all the different vips, he would appear all the vips, and we only want to appear him, the more expensive one. Or i have to negate permission in luckperms?

**Comment by msmanui** [comment] 2021-07-25 03:31
Also, relational placeholders are not working across server.
It does work if both players are on the same server, but then if i send a message in server 1, and the player is in server 2 he will read the message but the relational placeholder wont work. It only works if the players are on the same server.

**Comment by ElBananaa** [comment] 2021-07-25 17:21
> ¡Hey there, great plugin!
> 
> I was wondering how to do this:
> I have differents skyblock servers but all the chat is sync, right?
> If i want to do that for some survivals, and the chat to be sync BUT only tab-complete /msg for those in the skyblock server/survival server its possible? So it doesnt mix players. Should i uso a different mysql for the survivald and skyblocks?
> 
> Thanks and sorry for my spelling.

Hey!
I'm not sure to fully understand your first question. You would like to allow tab complete for PM across all the servers, without mixing players? I don't think this is possible. Separating your servers on multiple databases won't help in this case. It'll only disable other features such as cross-server chat.

Regarding the rank part, yes, you need to negate the permission in luckperms.
Finally, regarding relational placeholders, some are not supported at all.
Regading the others, I guess this is an expected behavior. Placeholders are not made to work throught bungeecord. However, I'm not sure about this, so we'll wait for Kangarko to give you more explanations about this.

**Comment by msmanui** [comment] 2021-07-25 17:25
Yes. I would like to create group of servers like
Group 1:
- sv1
- sv2
- Group 2:
- sv3
- sv4

So if u are at sv3, it will auto-tab complete for players in sv3/sv4. And if you are in sv1, it will auto-tab complete for sv1/sv2.
This is an essentials feature, as i have multiple servers in my network. So i expect to be added please. Basically, supporting cluster server... It really must-need feature for every network.

**Comment by ElBananaa** [comment] 2021-07-25 17:29
> Yes. I would like to create group of servers like
> Group 1:
> 
> * sv1
> * sv2
> * Group 2:
> * sv3
> * sv4
> 
> So if u are at sv3, it will auto-tab complete for players in sv3/sv4. And if you are in sv1, it will auto-tab complete for sv1/sv2.
> This is an essentials feature, as i have multiple servers in my network. So i expect to be added please. Basically, supporting cluster server... It really must-need feature for every network.

Alright, I understand it a bit better now. However, I don't think this is something possible right now. Let's wait for @kangarko to have a look at your suggestion

**Comment by msmanui** [comment] 2021-07-25 17:38
This plugin has that features
```
bungee_options:
  enable_bungee_mode: true
  server_id: sv2
  cluster_id: 0
  tab_complete_cross_server:
    enabled: true
    delay: 60
```
So every server with the same cluster_ID, will share the tab complete.
https://www.spigotmc.org/resources/⭐-huskhomes-1-17-x-⭐-simple-intuitive-teleportation-suite-with-cross-server-support.83767/

**Comment by msmanui** [comment] 2021-07-25 19:47
How do i add compatibility with **/clan chat**
When i do clan chat, i will enable my plugin's clan chat, but it will also write in the main global channel of chatcontrol

**Comment by ElBananaa** [comment] 2021-07-25 20:12
> How do i add compatibility with **/clan chat**
> When i do clan chat, i will enable my plugin's clan chat, but it will also write in the main global channel of chatcontrol

Which plugin do you use for your clans?
You may need to use the `Party` argument in your settings.yml file and create a channel with ChatControlRed, which works with some supported plugins.
```yaml
  # - Party: Makes the channel players only reach other players in the same party. This can work
  #          together with Range, but does not require that option. 
  #          Available values: factions-faction, plotsquared-plot, towny-town, towny-nation,
  #          mcmmo-party, towny-ally and lands-land
  #          Warning: The Party option does not work over BungeeCord!
```

If your plugin isn't listed above, try playing with the `Chat_Listener_Priority` in chatcontrolred, and the Chat_Listener of your clan plugin. Here's our wiki page dedicated to the listener priority edition : https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by msmanui** [comment] 2021-07-25 20:44
> > How do i add compatibility with **/clan chat**
> > When i do clan chat, i will enable my plugin's clan chat, but it will also write in the main global channel of chatcontrol
> 
> Which plugin do you use for your clans?
> You may need to use the `Party` argument in your settings.yml file and create a channel with ChatControlRed, which works with some supported plugins.
> 
> ```yaml
>   # - Party: Makes the channel players only reach other players in the same party. This can work
>   #          together with Range, but does not require that option. 
>   #          Available values: factions-faction, plotsquared-plot, towny-town, towny-nation,
>   #          mcmmo-party, towny-ally and lands-land
>   #          Warning: The Party option does not work over BungeeCord!
> ```
> 
> If your plugin isn't listed above, try playing with the `Chat_Listener_Priority` in chatcontrolred, and the Chat_Listener of your clan plugin. Here's our wiki page dedicated to the listener priority edition : https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

I tried every setting but is not working except with value 'MONITOR'. What is that specifically?

**Comment by ElBananaa** [comment] 2021-07-26 13:19
> > > How do i add compatibility with **/clan chat**
> > > When i do clan chat, i will enable my plugin's clan chat, but it will also write in the main global channel of chatcontrol
> > 
> > 
> > Which plugin do you use for your clans?
> > You may need to use the `Party` argument in your settings.yml file and create a channel with ChatControlRed, which works with some supported plugins.
> > ```yaml
> >   # - Party: Makes the channel players only reach other players in the same party. This can work
> >   #          together with Range, but does not require that option. 
> >   #          Available values: factions-faction, plotsquared-plot, towny-town, towny-nation,
> >   #          mcmmo-party, towny-ally and lands-land
> >   #          Warning: The Party option does not work over BungeeCord!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If your plugin isn't listed above, try playing with the `Chat_Listener_Priority` in chatcontrolred, and the Chat_Listener of your clan plugin. Here's our wiki page dedicated to the listener priority edition : https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
> 
> I tried every setting but is not working except with value 'MONITOR'. What is that specifically?

Hey!
The MONITOR listener priority is simply the higher listener priority for the plugin. Basically, it means the first plugin to be checked when something happens in the chat is ChatControlRed.

**Comment by ElBananaa** [comment] 2021-07-29 16:59
Closing this issue since it looks like it's been fixed.

**Closed as completed by ElBananaa** 2021-07-29 16:59 UTC
