### ISSUE TITLE
Not an issue as such, more a feature request

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl#157] opened 2016-11-20 11:01 UTC
I use the DiscordSRV plugin which connects in game chat with our discord channel. Has been working flawless in both HeroChat and LegendChat but I was told that ChatControl was better so I switched. As it turns out the channel way is not supported and it needs a hook?

https://github.com/Scarsz/DiscordSRV/tree/master/src/main/java/com/scarsz/discordsrv/hooks/chat

Is that something that might happen or should I ditch ChatControl? Hope not as I just paid for the pro version.

**Comment by kangarko** [comment] 2016-11-20 14:07
Duplicate of a ticket in the pro-section.

**Closed by kangarko** 2016-11-20 14:07 UTC
