### ISSUE TITLE
1.16.4: Nicknames not working in third party plugins

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#359] opened 2020-12-23 21:18 UTC
Latest release breaks the nicknames within McMMO party chat again:

![image](https://user-images.githubusercontent.com/5664135/103037684-b9beb600-456c-11eb-9f26-ff59058ef0e8.png)

Also breaks for CMI now. Both plugins can no longer find the nickname.

Just when it all worked fine on the previous release..

Minecraft 1.16.4, Bungee and mysql.

**Comment by Sikatsu** [comment] 2020-12-23 21:28
Also breaks for CMI now. Both systems can no longer find the nickname.

**Comment by kangarko** [comment] 2020-12-24 07:47
Will add a Change_Displayname toggle to turn this off.

**Comment by Sikatsu** [comment] 2020-12-24 11:38
This doesn't fix anything, whether I set it to true or false. Even after a restart.

Nicknames won't work in CMI and McMMO.. the plugins can not find ChatControl's nickname.

**Comment by kangarko** [comment] 2020-12-27 17:06
![mcm](https://user-images.githubusercontent.com/1918426/103175937-38b63600-486e-11eb-8305-b1beb86158e4.gif)
Sorry how can I reproduce this? I have Change_Displayname on false in settings.yml

**Comment by Sikatsu** [comment] 2020-12-27 18:15
I would like it to show the nickname in CMI's messages like AFK and McMMO. As shown in your gif, it doesn't do that. It shows your minecraft name instead. Whether I set it to false or true, this behaviour doesn't change.

**Comment by Sikatsu** [comment] 2020-12-29 17:59
Can this be reopened?

**Comment by ElBananaa** [comment] 2020-12-29 18:32
Hey!

As you asked, I'm reopening this issue. However, make sure you are using latest version for both CMI and CHC-Red. Also make sure that you didn't make any mistakes in your configs.

**Comment by Sikatsu** [comment] 2020-12-29 18:35
Thanks! It worked on version .10 I think, kangarko fixed it in that version. And .11 it is broken again, CMI and McMMO are updated. ^^

**Comment by kangarko** [comment] 2020-12-30 19:29
Thanks will be fixed!

**Comment by Sikatsu** [comment] 2020-12-30 21:08
I have no clue what you've changed eachtime, but this still doesn't work:

![image](https://user-images.githubusercontent.com/5664135/103381239-84294800-4aeb-11eb-80db-5e48827475b1.png)


ChatControl's nickname doesn't show in McMMO's party chat, nor in CMI's afk message. In version .10 this worked fine.

I tried both with change_displayname on true and false and rebooting the server.

**Comment by ElBananaa** [comment] 2020-12-30 21:34
> I have no clue what you've changed eachtime, but this still doesn't work:
> 
> ![image](https://user-images.githubusercontent.com/5664135/103381239-84294800-4aeb-11eb-80db-5e48827475b1.png)
> 
> ChatControl's nickname doesn't show in McMMO's party chat, nor in CMI's afk message. In version .10 this worked fine.
> 
> I tried both with change_displayname on true and false and rebooting the server.

Issue apparently still unfixed even on the latest version. I tried with the latest version and McMMO (Reborn), and I can confirm.
Reopening it.

**Comment by kangarko** [comment] 2020-12-31 06:56
Have you tried setting your nicks again? What I added, is a call to CMI and Essentials that is only called when using /tag nick again.

**Comment by kangarko** [comment] 2020-12-31 06:57
I have no idea how it came to work earlier, we did not have such a call. Now we tell CMI and Essentials that the user's nickname has changed.

**Comment by Sikatsu** [comment] 2020-12-31 08:48
It's just very odd, because in .9 when I talked to you about the bukkit call getDisplayname() nossr from mcmmo mentioned, you fixed it in .10, but it breaks again in .11

It's not just CMI and essentials but also mcmmo and other third party plugins, none of them can find chatcontrol's nickname, it indeed works when setting the nickname again though. Is it not fixable without that?

**Comment by Sikatsu** [comment] 2020-12-31 12:08
![unknown-13](https://user-images.githubusercontent.com/5664135/103409843-e7a58b00-4b68-11eb-9ed8-0e87060e34d3.png)
![unknown-19](https://user-images.githubusercontent.com/5664135/103409913-3c490600-4b69-11eb-816d-72bb32d25da8.png)

A player set his nickname again with color, then changed the color but party chat wouldn't update.

He then reset his nickname, which also won't update in the party chat.

**Comment by Malachiel87** [comment] 2021-01-01 11:55
is this issue can be related to plotsquared chat too? nicknames don't work here, nicky ones yes

**Comment by ElBananaa** [comment] 2021-01-01 16:23
Someone made a suggestion about this issue: #451.
I closed their suggestion since this is a suggestion regarding an issue that's already being investigating.


> is this issue can be related to plotsquared chat too? nicknames don't work here, nicky ones yes

Apparently it shouldn't since the plugin should tell third party plugins that the user has a nick.

**Comment by kangarko** [comment] 2021-01-04 17:36
It can't be fixed without making players set their nicknames again, apology. This is because we make a call to set a player's nick to CMI and Essentials explicitly when the change it.

If you guys want — I can add that call when the player joins and he's got a nick, so that they won't be forced to set it again?

**Comment by Sikatsu** [comment] 2021-01-04 17:38
That would be nice. But did you also see my other message?

Third party plugins (in this example mcmmo) can not find the updated nickname.

https://github.com/kangarko/ChatControl-Red/issues/359#issuecomment-752940175

**Comment by Sikatsu** [comment] 2021-01-04 17:39
In version .10 this whole issue was fixed, I don't understand why it was reverted and half broken since version .11 :(

**Comment by ElBananaa** [comment] 2021-01-04 17:39
> That would be nice. But did you also see my other message?
> 
> Third party plugins (in this example mcmmo) can not find the updated nickname.
> 
> [#359 (comment)](https://github.com/kangarko/ChatControl-Red/issues/359#issuecomment-752940175)

I just tried, again, and it looks like the nickname is correctly applied in partychat this time.

**Comment by Sikatsu** [comment] 2021-01-04 17:42
Yes, but change your nickname or nickname's color without performing a restart, reload or anything. As shown in the picture, public chat updates accordingly, mcmmo's party chat and other plugins still use the old nickname. Might be that the refresh is just really really slow.

However, it definitely doesn't function as it should..

**Comment by ElBananaa** [comment] 2021-01-04 17:49
> Yes, but change your nickname or nickname's color without performing a restart, reload or anything. As shown in the picture, public chat updates accordingly, mcmmo's party chat and other plugins still use the old nickname. Might be that the refresh is just really really slow.
> 
> However, it definitely doesn't function as it should..

Well, actually it works for me, even without a restart, I just had to change my nick, and it was updated in the partychat without any restart/reload or anything else..

**Comment by Sikatsu** [comment] 2021-01-04 17:58
![unknown-25](https://user-images.githubusercontent.com/5664135/103564427-c0c7bb80-4ebe-11eb-968b-812159713366.png)
Definitely doesn't work, until I relog then it updates.

**Comment by ElBananaa** [comment] 2021-01-04 18:03
> ![unknown-25](https://user-images.githubusercontent.com/5664135/103564427-c0c7bb80-4ebe-11eb-968b-812159713366.png)
> Definitely doesn't work, until I relog then it updates.

Weird. That might be related to you config maybe? But for sure it works for me. As I said, I just had to change my nick using `/nick Test` and then it updated it in the party chat.
Anyways, as Kangarko said, he'll probably add a call to get the nick on the player login.

**Comment by Sikatsu** [comment] 2021-01-04 18:05
Really odd, there isn't much about this in the configuration. Definitely an issue for me though, maybe kangarko knows why :/

**Comment by Sikatsu** [comment] 2021-01-07 14:37
This works in public chat, but not in mcmmo's party chat and CMI's afk (and other) messages.

![image](https://user-images.githubusercontent.com/5664135/103904918-38375e00-50fe-11eb-9285-9421c00d68cc.png)
![image](https://user-images.githubusercontent.com/5664135/103904927-3b324e80-50fe-11eb-94da-01c8b540550a.png)

**Comment by kangarko** [comment] 2021-01-07 17:07
I've added the call on login, please let me know the results from the next release!

**Comment by Sikatsu** [comment] 2021-01-07 17:12
Well, a relog already fixes the problem. Currently if you change your nickname, it won't update in mcmmo/cmi until you relog on the server. So a call on login, won't change I think?

**Comment by Sikatsu** [comment] 2021-01-07 20:28
Well, nothing changed, a relog works indeed like before, but without it my nickname will not update in third party plugins.
This is not an issue with the old nickname plugin I had so there must be some way to fix..

![image](https://user-images.githubusercontent.com/5664135/103941522-42be1b80-512f-11eb-99a6-07f1be690bd4.png)

**Comment by kangarko** [comment] 2021-01-08 09:19
Can you try this - enable Tab_List -- this will invoke some additional code changing display names. Next version will always invoke this depending on the Change_Displayname option as opposed to Tab_List.

**Comment by Sikatsu** [comment] 2021-01-08 09:31
I can, but I use a different plugin for tab list and rather not have the nicknames show up in the tab list.

Hopefully the next version will solve this

**Comment by kangarko** [comment] 2021-01-08 09:49
Just released :)

**Comment by Sikatsu** [comment] 2021-01-09 11:26
It's sort of fixed, but it now applies the rank in every message as well for party chat. It should exclude adding the rank to messages, of course.

![unknown-34](https://user-images.githubusercontent.com/5664135/104090247-d26de200-5275-11eb-8a38-b4fe07746a12.png)
![unknown-24](https://user-images.githubusercontent.com/5664135/104090248-d568d280-5275-11eb-935f-77f932bd67d1.png)

**Comment by Sikatsu** [comment] 2021-01-09 12:52
![unknown-12](https://user-images.githubusercontent.com/5664135/104092085-eae3f980-5281-11eb-9780-639174485b17.png)
Even colors the name above a players head..

**Comment by Malachiel87** [comment] 2021-01-09 12:53
still not working on plotsquared chat

**Comment by Malachiel87** [comment] 2021-01-10 23:10
Working on plotsquared chat, but nick is not updated until i restart the server

**Comment by kangarko** [comment] 2021-01-12 08:43
I made the following changes:

1: You can now disable Change_Customname (probably this is putting the name above players)
2: We now update the nick each time when display name is updated

<img width="778" alt="Screenshot 2021-01-12 at 09 42 11" src="https://user-images.githubusercontent.com/1918426/104290293-78aa2980-54ba-11eb-9f77-a83328121901.png">

Let me know how the next version will go! So sorry that this takes so long :/

**Comment by Sikatsu** [comment] 2021-01-12 08:44
Will it also fix showing the rank in front of every message and in party chat? I'd like it to show only the nickname as normal. I'll test the new version and hope it's solved, as it currently looks very chaotic on my server haha. Thanks!

**Comment by kangarko** [comment] 2021-01-12 09:25
I don't know, cannot test with all third part integrations right now. Just test disabling Change_Displayname, then Change_Customname and finally Tab_List.Enabled flags to see if one of those prevents this

**Comment by Sikatsu** [comment] 2021-01-12 09:29
It happens with any integration that is able to show nicknames, as of the last version it will pull the rank name through vault/luckperms and show it in front of your nickname everywhere.

I'll test around..

**Comment by Sikatsu** [comment] 2021-01-12 09:50
Still not solved, ranks still show up and the name above a players head still gets colored and changed. 

This is due to Change_Displayname on true, but if on false, nicknames won't work at all with third party plugins.

Change_Customname doesn't work at all, whether false or true it still changes the color above someones head.

![image](https://user-images.githubusercontent.com/5664135/104298149-ef97f000-54c3-11eb-8f79-ab966d71deb0.png)

**Comment by Sikatsu** [comment] 2021-01-14 19:52
Debug to test my setup:

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5816698/debug.zip)

**Comment by kangarko** [comment] 2021-01-17 13:07
Thanks so much! Got to it this today early as promised and here's results from the next version:

https://www.loom.com/share/20b5283eb09d45b3b2f717749fa9c774

Lemme know if there's anything I've missed and be sure to test the next version once it's out :)

**Comment by Sikatsu** [comment] 2021-01-17 14:22
Hey Matej! First, bless you! Second, it seems to work all fine from the short testing I was able to do today.

Thank you very much - hopefully no new issues pop up.

**Comment by kangarko** [comment] 2021-01-20 14:40
That is just pure golden news to me <3

**Closed as completed by kangarko** 2021-01-20 14:40 UTC
Labels: work-in-progress
