### ISSUE TITLE
command.gs don't import rules and message swear bug

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#746] opened 2021-02-27 16:18 UTC
Minecraft Version: 1.16.5 paper 498
MySQL: true
BungeeCord: true
chatcontrol:10.2.7

you can see the issue and debug posted on this post
https://github.com/kangarko/ChatControl-Red/issues/740

**Comment by ElBananaa** [comment] 2021-02-27 16:34
> Minecraft Version: 1.16.5 paper 498
> MySQL: true
> BungeeCord: true
> chatcontrol:10.2.7
> 
> you can see the issue and debug posted on this post
> #740

Please update to the latest version of the plugin in order to make sure this issue wasn't already fixed in it.

**Comment by FakEEE14** [comment] 2021-02-27 16:43
it is latest https://www.mc-market.org/resources/18217/

**Comment by ElBananaa** [comment] 2021-02-27 17:27
> it is latest https://www.mc-market.org/resources/18217/

It is, right, thought you were using 10.2.6

**Comment by kangarko** [comment] 2021-03-03 16:49
I don't understand your ticket clearly, but assuming you could not get the swear filter to work in /tell, I tested this for you and it works fine on your setup:

![a](https://i.imgur.com/X9GUN0e.png)

Ensure you did not give yourself or players bypass permissions for this. If I am mistaken comment below please.

**Closed as completed by kangarko** 2021-03-03 16:49 UTC

**Comment by ElBananaa** [comment] 2021-03-03 17:05
> I don't understand your ticket clearly, but assuming you could not get the swear filter to work in /tell, I tested this for you and it works fine on your setup:
> 
> ![a](https://camo.githubusercontent.com/5781bf10ad4b90817382a258442de91b05b30b860ec5f7ad6e7f3d2fbb9f4c42/68747470733a2f2f692e696d6775722e636f6d2f583947554e30652e706e67)
> 
> Ensure you did not give yourself or players bypass permissions for this. If I am mistaken comment below please.

Well basically, he said that the `@import global` doesn't seem to be working in the command rules. Someone reported something similar on discord (I can't find the post unfortunately), and said that copying the rules from the global.rs file to the commands.rs file fixed the issue.

**Comment by FakEEE14** [comment] 2021-03-03 18:47
but my players are able to send invites with /msg , idk why

**Comment by kangarko** [comment] 2021-03-04 16:46
@ElBananaa I cannot reproduce this error: https://i.imgur.com/13Ejamn.png

Likely caused by another plugin or something else blocking our check. Tell people to use Paper (not any other fork) and try only using ChatControl Red, thank you.

@FakEEE14 what do you mean by sending invites? I tried to re-read this commit's history but it's still unclear to me, sorry.

**Comment by FakEEE14** [comment] 2021-03-04 21:13
discord invite links

**Comment by kangarko** [comment] 2021-03-09 15:31
Just to be clear - you want to _stop_ players from sending Discord invite links via /msg ? If that is true, please provide an example /msg command with the message that got passed but it should not.
