### ISSUE TITLE
1.18.1: Plugin not loading

### ISSUE THREAD

**Issue by masterhacka** [kangarko/ChatControl#1601] opened 2022-01-02 15:31 UTC
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

I have the following issue in server log: https://pastebin.com/88eyCURd
This is the ChatControl error log: https://pastebin.com/MEjy24jy

Unfortunately the plugin isn't loading on paperspigot. I am using the newest version of apper and ChatControl Red.

**Comment by Terminal-Access** [comment] 2022-01-02 15:52
Dupe of previously reported [Bug](https://github.com/kangarko/ChatControl-Red/issues/1598)

**temp work around:** if using paper downgrade to build 119 or lower.

**Comment by ElBananaa** [comment] 2022-01-02 16:43
Hey,
As said above, please downgrade to paper 1.18.1 b119.
We'll keep you update about this issue on #1598

**Closed as completed by ElBananaa** 2022-01-02 16:43 UTC
