### ISSUE TITLE
1.8, 1.12, 1.17, 1.20: Receivers still get empty messages when display conditions

### ISSUE THREAD

**Issue by gre3x** [kangarko/ChatControl#2651] opened 2024-04-17 00:35 UTC
### "/version ChatControlRed" - plugin version

10.25.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

None

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15004022/debug.zip)

### Information about the issue/bug

After updating to version 10.25.6 from 10.24.5, these features no longer work:
- Improve | No longer sends empty messages to chat if your chat format is empty depending on your display conditions.
- Improve | Better detection at not sending empty messages, now evaluating whether the message is empty per-receiver's format conditions.

Specifically, the format that has stopped working for filtering out the messages is 'global-chat.yml` in my configs (see debug.zip).
The is not supposed to not send a message to the player if all parts of the message are filtered out by the `Receiver_Condition`. In 10.24.5, that has stopped working.

Below is the full filter that does work as a condition, but still sends the empty message (even though it is not supposed to send an empty message according to the above change logs). And it used to not send an empty message in version 10.24.5:
```
    Receiver_Condition: '''{advanciuschat_canview_{sender}}'' == ''true'''
```

Note that this did NOT happen in version 10.24.5

![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/c0d739d0-e98a-49e0-b553-8127ca3fb5a4)

**Comment by kangarko** [comment] 2024-04-17 07:45
Duplicate of https://github.com/kangarko/ChatControl-Red/issues/2647

**Closed as completed by kangarko** 2024-04-17 07:45 UTC
