### ISSUE TITLE
1.12.2: Join messages shows twice after updating BungeeControl

### ISSUE THREAD

**Issue by marekvac** [kangarko/ChatControl#955] opened 2021-05-07 07:14 UTC
Minecraft Version: Mohist 1.12.2
MySQL: true
BungeeCord: true

Chc debug: https://ufile.io/jnpz5aer

After updating chatcontrol red from version 10.3.3 to latest (10.3.8), I see two join messages. Both are simmilar and at 100% they're from both chatcontrol, because after disabling chatcontrol plugin, I haven't seen any join messages. I enabled option 'Delay_Join_Message_Until_Logged' because I have AuthMe on my server and now I see one join message immediately after I join and the second one after I log in via /login.

I figured it was BungeeControl causing it, after disabling it, I see only one join message, the right delayed one.
In BungeeControl config I have disabled all messages.
My BungeeControl confing: https://pastebin.com/ZEp3jUNs

There are also showing unwanted messages in bungeecord console - after player joined to server BungeeControl logs 'JOINING' and after player quit 'QUIT'. This is also since new update.

**Comment by kangarko** [comment] 2021-05-07 14:12
I will remove the JOINING and QUIT forgotten log messages, sorry about them.

Set Integration.AuthMe.Delay_Join_Message_Until_Logged to false, as well as leave BungeeControl's config.yml Messages key on false. Will you still be seeing doubled join messages?

Without AuthMe or with these option on false, I am only getting one player message at a time.

<img width="229" alt="Screenshot 2021-05-07 at 16 12 06" src="https://user-images.githubusercontent.com/1918426/117462450-fbb22c80-af4e-11eb-9106-a26b1bdc3af6.png">

**Comment by kangarko** [comment] 2021-05-07 14:12
Also try on Paper not the fork you're using.

**Comment by marekvac** [comment] 2021-05-07 15:04
Yes, without AuthMe I still see join messages twice (now are both displayed instantly). 

Unfortunately I can't use Paper, because I have modded server, so I must use this hybrid cores.

**Comment by marekvac** [comment] 2021-05-07 15:15
And the problem is only about the join messages. The quit messages shows correctly, only once.

**Comment by ElBananaa** [comment] 2021-05-07 17:34
> And the problem is only about the join messages. The quit messages shows correctly, only once.

Hey!
Could you try this to reproduce this issue with your entire chatcontrol actual setup, but under a local server, with the latest version of paper?
If this doesn't happen in this case, then I guess this would mean that this is somehow related to your fork, and unfortunately, there isn't much Kangarko can do about it since he can't provide support for too many different server softwares.

**Comment by marekvac** [comment] 2021-05-07 22:44
Ok, so on latest Paper with bungeecord I was able to reproduce a similar issue.

I put chatcontrol with vault on paper and bungeecontrol on bungeecord. Enabled bungeecord in spigot.yml.

First I tried my chc settings, but on empty new empty database. Next time I tried it with clear chc settings in which I enabled Integration.BungeeCord.Enabled and mysql. Both times have the same result. It's a little bit complicated..

**My steps to reproduce, tested on two players (player A, B)**
Put ChatControl on paper and BungeeControl on bungeecontrol.
Enable bungeecoord in chc settings.yml and in spigot.yml
Enable mysql in chc
Now the mysql is empty.
1. After player A joined, I see two messages. After player B joined I see two messages.
Both players disconnected.
2. Now every next time they're joined I see only one message.
I restarted the paper server.
3. First player which joins (doesn't matter if it was player A or B), chc shows two join messages. For the second one it only shows one.
4. After removing player A from database and restarted paper again, player B joined to server first - chc shows two messages. When player A joined it shows only one message. Same result when players switched.
5. After removing both players from database and restarted paper, I have same result as in step 1.

I hope you will understand that, my english isn't so good. If it doesn't make sense to you, for me neither, but that's exactly what happened to me.

After disabing Integration.BungeeCord.Enabled in settings.yml or disabling bungeecontrol, is showing up only one message every time.

**Comment by ElBananaa** [comment] 2021-05-08 00:15
> Ok, so on latest Paper with bungeecord I was able to reproduce a similar issue.
> 
> I put chatcontrol with vault on paper and bungeecontrol on bungeecord. Enabled bungeecord in spigot.yml.
> 
> First I tried my chc settings, but on empty new empty database. Next time I tried it with clear chc settings in which I enabled Integration.BungeeCord.Enabled and mysql. Both times have the same result. It's a little bit complicated..
> 
> **My steps to reproduce, tested on two players (player A, B)**
> Put ChatControl on paper and BungeeControl on bungeecontrol.
> Enable bungeecoord in chc settings.yml and in spigot.yml
> Enable mysql in chc
> Now the mysql is empty.
> 
> 1. After player A joined, I see two messages. After player B joined I see two messages.
>    Both players disconnected.
> 2. Now every next time they're joined I see only one message.
>    I restarted the paper server.
> 3. First player which joins (doesn't matter if it was player A or B), chc shows two join messages. For the second one it only shows one.
> 4. After removing player A from database and restarted paper again, player B joined to server first - chc shows two messages. When player A joined it shows only one message. Same result when players switched.
> 5. After removing both players from database and restarted paper, I have same result as in step 1.
> 
> I hope you will understand that, my english isn't so good. If it doesn't make sense to you, for me neither, but that's exactly what happened to me.
> 
> After disabing Integration.BungeeCord.Enabled in settings.yml or disabling bungeecontrol, is showing up only one message every time.

Haha, no worries, that's crystal clear.
It looks like a really weird issue. I don't really know if this is related to another plugin, your server version, your bungee version, or if this is basically a plugin issue. I suggest you wait for Kangarko so he could take a deeper look at your issue once he gets back on github issues (probably on monday/tuesday ^^)

**Comment by kangarko** [comment] 2021-05-11 16:31
Sorry about the delay, are you using Redis by the way? Are both of the two messages appearing on the same server?

**Comment by marekvac** [comment] 2021-05-12 11:56
No, I'm not using redis. Yes, the messages appearing on the same server.

**Comment by kangarko** [comment] 2021-05-17 15:52
Hey! This is fixed in Messages_New option of BungeeControl. Do not use the player join/kick messages on Bukkit. Only use the Messages_New option (set Apply_On to [join, quit, switch] and then configure your RS files in messages/ in BungeeControl folder on your network.

**Closed as completed by kangarko** 2021-05-17 15:52 UTC
Labels: work-in-progress
