### ISSUE TITLE
[OUTDATED PLUGIN VERSION] 1.16.5: Loading the plugin is extremely slow

### ISSUE THREAD

**Issue by martineriksson** [kangarko/ChatControl#1519] opened 2021-12-02 17:23 UTC
When starting the server, ChatControl gets stuck on something. Previously it has taken a few minutes, which is already very bad. The last time it took 18 minutes.

This is how it looks:

![Screen Shot 2021-12-02 at 18 12 53](https://user-images.githubusercontent.com/218341/144471543-a2ff057e-073f-425d-9980-41aff30476fa.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment] 2021-12-02 17:37
Please post me a screen of your phpmyadmin chatcontrol tables like this:

![a](https://i.imgur.com/yeeJQeI.png)

**Comment by martineriksson** [comment] 2021-12-02 18:20
I don't have phpmyadmin. Maybe you can tell me more specifically what you are looking for. I will do my best to provide the information you need.

**Comment by ElBananaa** [comment] 2021-12-02 18:36
> I don't have phpmyadmin. Maybe you can tell me more specifically what you are looking for. I will do my best to provide the information you need.

Well, your database seems pretty heavy, causing this very long loading time. So take a look at it to see which tables are the heavier and try to clean it a bit

**Comment by martineriksson** [comment] 2021-12-02 19:42
There is nothing much in the database. I only use it for Chat Control and for a permissions plugin and another small thing like that.

But in any case, what is Chat Control even doing here? What kind of operations are done in the name of "updating the database"? How could it possibly take 18 minutes?

**Comment by ElBananaa** [comment] 2021-12-03 01:14
> There is nothing much in the database. I only use it for Chat Control and for a permissions plugin and another small thing like that.
> 
> But in any case, what is Chat Control even doing here? What kind of operations are done in the name of "updating the database"? How could it possibly take 18 minutes?

Well, the database contains the logs, the userdata, and the mails, which can be somehow pretty heavy at some point.
However, the plugin shouldn't take 18 minutes to load, but in your case, there isn't `nothing much` in your database, and your screenshot proves it: the plugin is trying to load over 10k entries.
I'll run some tests on my end to make sure this isn't an issue related to the plugin, but accoding to the fact that you don't have access to phpmyadmin, I guess this issue is most likely caused by either your host offering a poor db host with low memory (ram) / bandwith and limited connections, or your server being slow itself (or even both, who knows)...

In the meantime, I'd suggest lowering the `Clear_Data_If_Inactive` to something like `Clear_Data_If_Inactive: 30 days` and `Log.Clean_After` to `Clean_After: 7 days`, this should hopefully decrease the db loading time.
If this is possible, I'd also suggest switching to MariaDB as it is much faster than MySQL for queries.

I'll keep you updated about the results of my tests.

**Comment by martineriksson** [comment] 2021-12-03 02:08
Thank you very much for your helpful replies and for looking into this matter!

The reason I don't have phpmyadmin is that I am administrating the server myself and I have not seen any reason to install that particular tool. However, this means that I have unlimited access to the database. Here are some current stats:

```
mysql> SELECT table_name, table_rows FROM information_schema.tables WHERE table_schema = 'chatcontrol';
+------------------+------------+
| TABLE_NAME       | TABLE_ROWS |
+------------------+------------+
| ChatControl      |        167 |
| ChatControl_Log  |      20306 |
| ChatControl_Mail |          0 |
+------------------+------------+

```

I guess we have different perspectives on what "much" means. In my world 20,000 rows in a database is a small number because any normal operation you make on that many rows takes at most a few seconds to execute. So my conclusion is that Chat Control must be doing something in this case which is not normal. Maybe a very inefficient way of querying the database?

I still don't understand what it is even supposed to be doing. What does "updating the database" mean? Why would it be doing something at load time which could take 5-10 minutes?

Thank you for the suggested configuration settings, I have made both of them now.

**Comment by ElBananaa** [comment] 2021-12-03 02:46
Alright, I just tried to replicate your issue on my side, with around 15k entries only in the log table, and the server instantly started.


However, I think I did find the reason of your issue: You're using a completely outdated version of the plugin. CHC-Red v10.2.1 was released ~10 months ago, and you are aproximately 50 versions behind the actual latest available release.

Please properly update the plugin (due to how old your version and your configs must be, I'd suggest making a backup, and doing a completely fresh install of the plugin with an empty db, then reconfiguring the plugin based on your old configs.).


I'm closing this issue, but feel free to keep commenting down below if you need anything else.

**Closed as completed** 2021-12-03 02:47 UTC

**Comment by kangarko** [comment] 2021-12-03 13:47
This was the issue, I added notes to this to its header:

![a](https://i.imgur.com/MI6Gprp.png)

Basically your table is too large for our cleaning algorithm, just disable it and when you want your table cleared just run a SQL query.

@ElBananaa something to take note :)

**Comment by martineriksson** [comment] 2021-12-03 13:50
Thank you very much @kangarko!

**Comment by kangarko** [comment] 2021-12-03 13:52
Let me know if that helps!
