### ISSUE TITLE
Database is just ugh

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#253] opened 2020-12-10 13:41 UTC
```
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true
```

![unknown](https://user-images.githubusercontent.com/29175381/101779625-691b7780-3aed-11eb-98d4-4d4792cc5797.png)

Someone changes their username and chatcontrol cant even handle it :(

**Comment by kangarko** [comment] 2020-12-10 13:50
You haven't followed our issue template: https://github.com/kangarko/ChatControl-Red/issues/2

**Comment by DoogiePC** [comment] 2020-12-10 23:14
also um, for some reason im being made to spy on global chat even though everyone can see it because it's global?

**Comment by kangarko** [comment] 2020-12-11 07:38
Okay, however please send the information from the template and steps to reproduce the first issue. So I assume you did /tag nick somenick and then you did some command that did not work? Which one?

Yes, you can spy on all channels including the global ones. However you should then not see the [spy] prefix before your message.

**Comment by DoogiePC** [comment] 2020-12-11 08:58
> Okay, however please send the information from the template and steps to reproduce the first issue. So I assume you did /tag nick somenick and then you did some command that did not work? Which one?
> 
> Yes, you can spy on all channels including the global ones. However you should then not see the [spy] prefix before your message.

To reproduce it change your username :/

Global never used to show up as spy because why would you need to spy on a channel everyone can see

**Comment by kangarko** [comment] 2020-12-15 09:47
I cannot reproduce the nick issue. Please provide the following data:

- Your MC version
- Are you using MySQL?
- Are you using Bungee?
- What command has been typed that failed when the player changed his nick?

**Comment by kangarko** [comment] 2020-12-15 09:52
Closing since you failed to provide this data MULTIPLE times now and we've wasted time. If you still need help, open a new ticket with the 4 questions from above must be answered.

**Closed as completed by kangarko** 2020-12-15 09:52 UTC
Labels: work-in-progress

**Comment by DoogiePC** [comment] 2020-12-15 13:51
mc version 1.16.4
yes im using mysql and bungee
everything fails because it doesn't recognise his new username as a player, it's not hard to reproduce, just change your username and login without restarting the server
