### ISSUE TITLE
1.16.4: Mysql - wrong message?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#448] opened 2020-12-31 22:23 UTC
Minecraft Version: 1.64.4
MySQL: true
BungeeCord: true

Hi, I've got this error when someone wrote:
```
[23:15:32] [Async Chat Thread - #30/INFO]: [standard] kebabisko_cz1: You spin me right 'round, babyRight 'round like a record, babyRight 'round, 'round, 'round
[23:15:32] [Craft Scheduler Thread - 511/INFO]: [ChatControlRed] ChatControlRed 10.1.14 encountered a MySQLSyntaxErrorException! Please check your error.log and report this issue with the information in that file.
[23:15:32] [Craft Scheduler Thread - 511/INFO]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'round,/ babyRight \\'round like a record,/ babyRight \\'round,/ \\'round,/ \\...' at line 1
[23:15:32] [Craft Scheduler Thread - 511/INFO]: at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.update(SimpleDatabase.java:282)
[23:15:32] [Craft Scheduler Thread - 511/INFO]: at org.mineacademy.chatcontrol.model.Database.insertLogValues(Database.java:120)
[23:15:32] [Craft Scheduler Thread - 511/INFO]: at org.mineacademy.chatcontrol.model.Log.lambda$write$0(Log.java:231)
[23:15:32] [Craft Scheduler Thread - 511/INFO]: at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
[23:15:32] [Craft Scheduler Thread - 511/INFO]: [ChatControlRed] !-----------------------------------------------------!
[23:15:32] [Craft Scheduler Thread - 511/INFO]: [ChatControlRed]  Error on updating MySQL with: INSERT INTO ChatControl_Log VALUES('Survival', '2020-12-31 23:15:32.556', 'chat', 'kebabisko_cz1', NULL, 'You spin me right \\'round,/ babyRight \\'round like a record,/ babyRight \\'round,/ \\'round,/ \\'round', 'standard', NULL, NULL)
[23:15:32] [Craft Scheduler Thread - 511/INFO]: [ChatControlRed] !-----------------------------------------------------!
https://pastebin.com/9EZyexKD
```

**Comment by altruiis** [comment] 2020-12-31 22:56
Also getting this issue. Seems to happen whenever a user sends a message with an apostrophe `'`

**Comment by ElBananaa** [comment] 2020-12-31 23:53
> Also getting this issue. Seems to happen whenever a user sends a message with an apostrophe `'`

Hey!
Happy new year!

I couldn't reproduce this with a sqlite setup, however, this might actually be caused by the mysql setup.
You could try to disable chat & pm logging under the log part in the settings file:
```
Log:
  
  # What player actions should be logged?
  # Options: chat, command, private_message, mail, sign, book, anvil
  Apply_On:
  - 'chat' <--- Remove this one
  - 'command'
  - 'private_message' <--- Remove this one
  - 'mail' 
  - 'sign'
  - 'book' 
  - 'anvil'
```
It should temporarily fix the issue until Kangaroo can take care of this issue.

**Comment by Malachiel87** [comment] 2021-01-03 10:13
same here on mysql happen only with accented names
[11:10:08 INFO]: [ChatControlRed] !-----------------------------------------------------!
[11:10:08 INFO]: [ChatControlRed]  Error on updating MySQL with: INSERT INTO ChatControl_Log VALUES('vanilla', '2021-01-03 11:10:08.936', 'chat', 'x_Elisabet_x', NULL, 'non me l\\'aspettavo', 'standard', NULL, NULL)
[11:10:08 INFO]: [ChatControlRed] !-----------------------------------------------------!

[11:10:10 INFO]: [ChatControlRed] !-----------------------------------------------------!
[11:10:10 INFO]: [ChatControlRed]  Error on updating MySQL with: INSERT INTO ChatControl_Log VALUES('vanilla', '2021-01-03 11:10:10.254', 'chat', 'Spefix', NULL, 'non se l\\'aspettava!', 'standard', NULL, NULL)
[11:10:10 INFO]: [ChatControlRed] !-----------------------------------------------------!

**Comment by kangarko** [comment] 2021-01-05 15:27
Thanks, will be fixed, we will strip out ' from the logs.

**Closed as completed by kangarko** 2021-01-05 15:27 UTC
