### ISSUE TITLE
1.19.2 : Command name

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2155] opened 2022-10-09 15:37 UTC
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello,

I use a command that restrict the use of commands that are not whitelisted (so you can't do /msg is "/msg" is not in whitelist)

So I added in whitelist :
- /msg
- /m
- /message
- /tell
- /ig
- /ignore

When player do one of theses command, it will send him the command explaination, the command work without issue, but it still tell "forbidden command", because behind the /msg it runs another command that I can't find.

I don't know if you understand, but as my plugin is translated in french, a screen won't really help.
But what command is executed when player do /msg, or /ignore ?

**Comment by ElBananaa** [comment] 2022-10-09 18:36
No commands are executed when you run /msg other than the msg command itself.
You may want to try with /tell but I doubt it'll change anything
Same with the ignore command. If you have an issue with this, this is most likely not related to chatcontrol/caused by chatcontrol.

Btw, there's no error message that includes "forbidden" in chatcontrol, so this is most likely caused by another plugin.
I'm closing this, but you can keep commenting down below if needed, we'll still receive notifications, so no need to open a new issue for this.

**Closed as not planned** 2022-10-09 19:33 UTC
