### ISSUE TITLE
1.17.1: DiscordToMinecraftChat Format?

### ISSUE THREAD

**Issue by lukaplayz** [kangarko/ChatControl#1184] opened 2021-07-27 04:30 UTC
Hello!
So I only have 1 channel called standard, and it is relaying those messages to Discord using DiscordSRV. If you type from Minecraft in chat it goes to Discord channel. If you type from Discord channel it goes to Minecraft chat looking wrong.
![image](https://user-images.githubusercontent.com/59068185/127095551-1c2178c1-89f8-491e-b5c9-ddf230b06a3f.png)

So this brings me to ask a question. How do I fix it so that it lets me customize the DiscordtoMinecraft Chat format?
I may provide any information you guys need! Thank you! :D

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment] 2021-07-27 16:23
> Hello!
> So I only have 1 channel called standard, and it is relaying those messages to Discord using DiscordSRV. If you type from Minecraft in chat it goes to Discord channel. If you type from Discord channel it goes to Minecraft chat looking wrong.
> ![image](https://user-images.githubusercontent.com/59068185/127095551-1c2178c1-89f8-491e-b5c9-ddf230b06a3f.png)
> 
> So this brings me to ask a question. How do I fix it so that it lets me customize the DiscordtoMinecraft Chat format?
> I may provide any information you guys need! Thank you! :D
> 
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: false

Hey!
This issue is caused by the fact that some placeholders can't be replaces since the message isn't sent from an ingame player.
To avoid showing placeholders that can't be replaced correctly, you can use the `Sender_Condition` argument in your format file to only send the parts with these placeholders if the player is ingame.
Here's an example with my own format file:
```yaml
Parts:
  delete-chat:
    Message: '&7[#cf0e00&lX&7] '
    Receiver_Permission: chatcontrol.removemessages
    Sender_Condition: '{sender_is_discord} == false'
    Hover:
    - '&cClick to remove this message.'
    Run_Command: /{label} internal remove {message_uuid}

  report-player:
    Message: '&c⚠ '
    Sender_Permission: chatcontrol.allowreport
    Sender_Condition: '{sender_is_discord} == false'
    Receiver_Permission: chatcontrol.allowreport
    Hover:
    - '&e&lClick to report &c{player}&e.'
    Suggest_Command: /report create {player}

  spies-prefix:
    Message: '&c&lSPY &8&l| '
    Receiver_Condition: '{player_is_spying_{channel}}'
    Sender_Condition: '{sender_is_discord} == false'
    Hover:
    - '&cClick to stop spying the &e{channel}&c channel.'
    Run_Command: /{label_spy} toggle chat {channel}

  tag:
    Message: '&7[{deluxetags_tag}&7] '
    Sender_Condition: '{sender_is_discord} == false'
    Hover:
    - '&7{player_prefix}{player_name} {player_suffix}'
    Sender_Condition: '''{player_has_tag}'' == ''Yes'''
```

If you want more informations about the `{sender_is_discord}` placeholder, here's our dedicated wiki page for our variables: https://github.com/kangarko/ChatControl-Red/wiki/Variables

Let me know if this helped and if I can close this issue.

**Comment by lukaplayz** [comment] 2021-07-27 17:53
> > Hello!
> > So I only have 1 channel called standard, and it is relaying those messages to Discord using DiscordSRV. If you type from Minecraft in chat it goes to Discord channel. If you type from Discord channel it goes to Minecraft chat looking wrong.
> > ![image](https://user-images.githubusercontent.com/59068185/127095551-1c2178c1-89f8-491e-b5c9-ddf230b06a3f.png)
> > So this brings me to ask a question. How do I fix it so that it lets me customize the DiscordtoMinecraft Chat format?
> > I may provide any information you guys need! Thank you! :D
> > Minecraft Version: 1.17.1
> > MySQL: false
> > BungeeCord: false
> 
> Hey!
> This issue is caused by the fact that some placeholders can't be replaces since the message isn't sent from an ingame player.
> To avoid showing placeholders that can't be replaced correctly, you can use the `Sender_Condition` argument in your format file to only send the parts with these placeholders if the player is ingame.
> Here's an example with my own format file:
> 
> ```yaml
> Parts:
>   delete-chat:
>     Message: '&7[#cf0e00&lX&7] '
>     Receiver_Permission: chatcontrol.removemessages
>     Sender_Condition: '{sender_is_discord} == false'
>     Hover:
>     - '&cClick to remove this message.'
>     Run_Command: /{label} internal remove {message_uuid}
> 
>   report-player:
>     Message: '&c⚠ '
>     Sender_Permission: chatcontrol.allowreport
>     Sender_Condition: '{sender_is_discord} == false'
>     Receiver_Permission: chatcontrol.allowreport
>     Hover:
>     - '&e&lClick to report &c{player}&e.'
>     Suggest_Command: /report create {player}
> 
>   spies-prefix:
>     Message: '&c&lSPY &8&l| '
>     Receiver_Condition: '{player_is_spying_{channel}}'
>     Sender_Condition: '{sender_is_discord} == false'
>     Hover:
>     - '&cClick to stop spying the &e{channel}&c channel.'
>     Run_Command: /{label_spy} toggle chat {channel}
> 
>   tag:
>     Message: '&7[{deluxetags_tag}&7] '
>     Sender_Condition: '{sender_is_discord} == false'
>     Hover:
>     - '&7{player_prefix}{player_name} {player_suffix}'
>     Sender_Condition: '''{player_has_tag}'' == ''Yes'''
> ```
> 
> If you want more informations about the `{sender_is_discord}` placeholder, here's our dedicated wiki page for our variables: https://github.com/kangarko/ChatControl-Red/wiki/Variables
> 
> Let me know if this helped and if I can close this issue.

Thank you so much, but sadly something isn't working. Do you mind taking a quick look at my format, and making it work so It has a different format for DiscordToMinecraft, because I tried what you said and It did not work :/

```
Parts:
  delete-chat:
    Message: '{marriagemaster_Status_Heart} '
    Hover: '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
    Receiver_Permission: chatcontrol.chat.deletebuttonsee
  marriageheartcute:
    Message: '{marriagemaster_Status_Heart} '
    Receiver_Permission: chatcontrol.chat.onlypeoplecanseethis
    Hover:
    - '&6Information about %player_name%...'
    - '&8&l| &7Rank: {vault_groupprefix}'
    - '&8&l| &7Tier: {ezrankspro_rankprefix}'
    - '&8&l| &7Pronouns: {pronouns_pronouns}'
    - ''
    - '&aClick to message this player...'
    Suggest_Command: '/tell {player_name} '
  tierlist:
    Message: '{ezrankspro_rankprefix} '
    Hover:
    - '&6Information about %player_name%...'
    - '&8&l| &7Rank: {vault_groupprefix}'
    - '&8&l| &7Tier: {ezrankspro_rankprefix}'
    - '&8&l| &7Pronouns: {pronouns_pronouns}'
    - ''
    - '&aClick to message this player...'
    Suggest_Command: '/tell {player_name} '
  prefix:
    Message: '{player_prefix}'
    Hover:
    - '&6Information about %player_name%...'
    - '&8&l| &7Rank: {vault_groupprefix}'
    - '&8&l| &7Tier: {ezrankspro_rankprefix}'
    - '&8&l| &7Pronouns: {pronouns_pronouns}'
    - ''
    - '&aClick to message this player...'
    Suggest_Command: '/tell {player_name} '
  player-name:
    Message: '{player_nick+}'
    #Message: "{player_name}"
    #Gradient: RED - YELLOW
    Hover:
    - '&6Information about %player_name%...'
    - '&8&l| &7Rank: {vault_groupprefix}'
    - '&8&l| &7Tier: {ezrankspro_rankprefix}'
    - '&8&l| &7Pronouns: {pronouns_pronouns}'
    - ''
    - '&aClick to message this player...'
    Suggest_Command: '/tell {player_name} '
  tags:
    Message: '{deluxetags_tag} '
    Sender_Condition: '{sender_is_discord} == false'
    Hover:
    - '&6Information about %player_name%...'
    - '&8&l| &7Rank: {vault_groupprefix}'
    - '&8&l| &7Tier: {ezrankspro_rankprefix}'
    - '&8&l| &7Pronouns: {pronouns_pronouns}'
    - ''
    - '&aClick to message this player...'
    Suggest_Command: '/tell {player_name} '
  message:
    Message: '&7» &f{player_suffix}{message}'
    Hover:
    - '&6Information about %player_name%...'
    - '&8&l| &7Rank: {vault_groupprefix}'
    - '&8&l| &7Tier: {ezrankspro_rankprefix}'
    - '&8&l| &7Pronouns: {pronouns_pronouns}'
    - ''
    - '&aClick to message this player...'
    Suggest_Command: '/tell {player_name} '

```

**Comment by lukaplayz** [comment] 2021-07-29 03:55
can someone please help sry if im asking too much but I need help ASAP

**Comment by ElBananaa** [comment] 2021-07-29 16:32
Hey!
Sorry I didn't see your message.
What do you mean by "it doesn't work"? What doesn't work exactly? What does it shows ingame? Could you provide us screenshots?

**Comment by lukaplayz** [comment] 2021-07-29 19:11
> Hey!
> Sorry I didn't see your message.
> What do you mean by "it doesn't work"? What doesn't work exactly? What does it shows ingame? Could you provide us screenshots?

Hello! So basically it doesn't fix the issue. It still looks like this 
![image](https://user-images.githubusercontent.com/59068185/127551617-66b5d2c8-e215-4092-9dec-fd97b3501d5f.png)
That image is the message from Discord to Minecraft. I want that to be formatted differently so there isn't placeholders in there that arent used.

**Comment by ElBananaa** [comment] 2021-07-29 19:35
> > Hey!
> > Sorry I didn't see your message.
> > What do you mean by "it doesn't work"? What doesn't work exactly? What does it shows ingame? Could you provide us screenshots?
> 
> Hello! So basically it doesn't fix the issue. It still looks like this
> ![image](https://user-images.githubusercontent.com/59068185/127551617-66b5d2c8-e215-4092-9dec-fd97b3501d5f.png)
> That image is the message from Discord to Minecraft. I want that to be formatted differently so there isn't placeholders in there that arent used.

Alright, try replacing `Sender_Condition: '{sender_is_discord} == false'` with `Sender_Condition: '{sender_is_player} == true'`

**Comment by lukaplayz** [comment] 2021-07-29 20:59
> > > Hey!
> > > Sorry I didn't see your message.
> > > What do you mean by "it doesn't work"? What doesn't work exactly? What does it shows ingame? Could you provide us screenshots?
> > 
> > 
> > Hello! So basically it doesn't fix the issue. It still looks like this
> > ![image](https://user-images.githubusercontent.com/59068185/127551617-66b5d2c8-e215-4092-9dec-fd97b3501d5f.png)
> > That image is the message from Discord to Minecraft. I want that to be formatted differently so there isn't placeholders in there that arent used.
> 
> Alright, try replacing `Sender_Condition: '{sender_is_discord} == false'` with `Sender_Condition: '{sender_is_player} == true'`

Thank you so sosososo much! It works!

**Comment by ElBananaa** [comment] 2021-07-30 02:21
> > > > Hey!
> > > > Sorry I didn't see your message.
> > > > What do you mean by "it doesn't work"? What doesn't work exactly? What does it shows ingame? Could you provide us screenshots?
> > > 
> > > 
> > > Hello! So basically it doesn't fix the issue. It still looks like this
> > > ![image](https://user-images.githubusercontent.com/59068185/127551617-66b5d2c8-e215-4092-9dec-fd97b3501d5f.png)
> > > That image is the message from Discord to Minecraft. I want that to be formatted differently so there isn't placeholders in there that arent used.
> > 
> > 
> > Alright, try replacing `Sender_Condition: '{sender_is_discord} == false'` with `Sender_Condition: '{sender_is_player} == true'`
> 
> Thank you so sosososo much! It works!

Glad it works!
I'm closing this issue, feel free to comment down below if you need anything else.

**Closed as completed by ElBananaa** 2021-07-30 02:21 UTC
