### ISSUE TITLE
Version: Mohist 1.12.2

### ISSUE THREAD

**Issue by JIMER228** [kangarko/ChatControl#2876] opened 2024-11-26 12:24 UTC
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hello. I ran into a problem that plugin does not perform any functionality on the server, although it works, there are no errors in the console and there are no error.log files. The bottom line is, I'm in formats/that.the yml in the prefix section did this like this -
  `prefix:
    Message: '{%luckperms_prefix%}'
    Hover:
    - '&7{%luckperms_prefix%}{player_name} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'`
   

### Steps to reproduce

An example of why the plugin does not work:

after I took away my "OP" rights, when sending messages to the chat, I was not given any warnings, etc., it didn't matter to everyone. 

The prefix is not displayed at all, whatever I did, I spent 4 hours solving the problem and it did not work.

**Comment by kangarko** [comment] 2024-11-26 18:31
Duplicate of https://github.com/kangarko/ChatControl-Red/issues/2875

**Closed as completed by kangarko** 2024-11-26 18:31 UTC
