### ISSUE TITLE
1.17.1: Huge performance issues from tab completer

### ISSUE THREAD

**Issue by AlessioGr** [kangarko/ChatControl#1508] opened 2021-11-28 20:38 UTC
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

I am getting a lot of performance issues from the TAB Completer: https://spark.lucko.me/DhmwXgZ3Ay

**Comment by kangarko** [comment] 2021-12-01 17:30
Tab complete less.

**Comment by kangarko** [comment] 2021-12-01 17:32
I was joking! Please send me your /chc debug file, I'd like to try reproducing on your setup. Looks like your tab-completer whitelist regex is slow. I recommend testing your whitelist, each line against regex101.com - it shows you how long processing the line took so you can optimize it.

**Comment by kangarko** [comment] 2021-12-02 14:47
Closing due to cleaning up, please follow my advice above. If you have questions, know that I am getting notified when you comment below.

**Closed as completed by kangarko** 2021-12-02 14:47 UTC
