### ISSUE TITLE
How do I format [item] to have brackets around it?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1576] opened 2021-12-22 14:14 UTC
I'm trying to wrap `[item]` with brackets so its separate in chat and that its formatted, but for some reason this requires javascript.
I tried creating a new variable and wrapping brackets either side, but this does not get printed out, only the name of the item gets printed out.
Otherwise I'm using the vanilla example.

```
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------

# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: message

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
Key: item

# The value the key will be replaced to. This uses JavaScript.
Value: |-
    // A valid JavaScript code follows below. You can use the "player" variable to get
    // Bukkit's player instance. 
    
    // Call the function
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      var air = Java.type("org.bukkit.Material").AIR;
     
      // Special support for throwing exceptions, you can begin the exception
      // with "event handled: ". We will cancel the event for you, in this case, the chat message,
      // and then send the message to the player that appears after that.
      if (item == null || item.getType() == air) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      // If the item has meta data and a custom name, show that name instead
      if (metadata != null && metadata.hasDisplayName())
        return metadata.getDisplayName();
    
      // Example of using Java classes to show custom names for custom types
      // JavaScript has to wrap all Java classes using Java.type, see 
      // https://winterbe.com/posts/2014/04/05/java8-nashorn-tutorial/#invoking-java-methods-from-javascript
      var stone = Java.type("org.bukkit.Material").STONE;
       
      // You can, for example, print custom names for certain materials
      //if (item.getType() == stone)
      //  return "My Shiny Little Stone";
    
      // We use a class that is packed in Spigot server's JAR to capitalize our item
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
      var wrapme = wordUtils.capitalize(name);
      var formattedName = "["+wrapme+"]";
      // Return the item name deducted from item's type, capitalized
      return formattedName;
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

# What texts should be displayed when we hover the mouse
# over this variable in the chat
Hover: []

# What ItemStack should be displayed when we hover the mouse over this variable in the chat
Hover_Item: player.getItemInHand()

# What website URL should be opened when we click with the mouse
# on this variable in the chat
Open_Url: ''

# What command should appear in the player command box on his screen
# if he clicks on this variable in the chat
Suggest_Command: ''

# What command should run as the sender when he clicks the mouse on this variable?
# Minecraft only supports 1 command!
Run_Command: ''

```

I'm surprised javascript was picked for this, when the chat plugin replies so heavily on PlaceHolderAPI dependencies for gradients etc, seeing that the `player` placeholder has all this item information. https://api.extendedclip.com/expansions/player/
Javascript makes this overly complex.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment] 2021-12-22 17:31
Hey, give this a shot:
```yaml
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------

# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: message

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
Key: item

# The value the key will be replaced to. This uses JavaScript.
Value: |-
    // A valid JavaScript code follows below. You can use the "player" variable to get
    // Bukkit's player instance. 
    
    // Call the function
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      var air = Java.type("org.bukkit.Material").AIR;
     
      // Special support for throwing exceptions, you can begin the exception
      // with "event handled: ". We will cancel the event for you, in this case, the chat message,
      // and then send the message to the player that appears after that.
      if (item == null || item.getType() == air) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      // If the item has meta data and a custom name, show that name instead
      if (metadata != null && metadata.hasDisplayName())
        return metadata.getDisplayName();
    
      // Example of using Java classes to show custom names for custom types
      // JavaScript has to wrap all Java classes using Java.type, see 
      // https://winterbe.com/posts/2014/04/05/java8-nashorn-tutorial/#invoking-java-methods-from-javascript
      var stone = Java.type("org.bukkit.Material").STONE;
       
      // You can, for example, print custom names for certain materials
      //if (item.getType() == stone)
      //  return "My Shiny Little Stone";
    
      // We use a class that is packed in Spigot server's JAR to capitalize our item
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
      var wrapme = wordUtils.capitalize(name);
      var formattedName = "[" + wrapme + "]";
      // Return the item name deducted from item's type, capitalized
      return "[" + formattedName + "]";
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

# What texts should be displayed when we hover the mouse
# over this variable in the chat
Hover: []

# What ItemStack should be displayed when we hover the mouse over this variable in the chat
Hover_Item: player.getItemInHand()

# What website URL should be opened when we click with the mouse
# on this variable in the chat
Open_Url: ''

# What command should appear in the player command box on his screen
# if he clicks on this variable in the chat
Suggest_Command: ''

# What command should run as the sender when he clicks the mouse on this variable?
# Minecraft only supports 1 command!
Run_Command: ''

**Comment by TomLewis** [comment] 2021-12-22 21:41
Hey Banana, sadly this did not work.

![2021-12-22_21 41 08](https://user-images.githubusercontent.com/144046/147158423-03f5f929-48c3-4807-8f2b-4881fa4e7834.png)

**Comment by ElBananaa** [comment] 2021-12-22 21:58
Hey, weird, can you please try this:
```yaml
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------

# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: message

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
Key: item

# The value the key will be replaced to. This uses JavaScript.
Value: |-
    // A valid JavaScript code follows below. You can use the "player" variable to get
    // Bukkit's player instance. 
    
    // Call the function
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      var air = Java.type("org.bukkit.Material").AIR;
     
      // Special support for throwing exceptions, you can begin the exception
      // with "event handled: ". We will cancel the event for you, in this case, the chat message,
      // and then send the message to the player that appears after that.
      if (item == null || item.getType() == air) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      // If the item has meta data and a custom name, show that name instead
      if (metadata != null && metadata.hasDisplayName())
        return metadata.getDisplayName();
    
      // Example of using Java classes to show custom names for custom types
      // JavaScript has to wrap all Java classes using Java.type, see 
      // https://winterbe.com/posts/2014/04/05/java8-nashorn-tutorial/#invoking-java-methods-from-javascript
      var stone = Java.type("org.bukkit.Material").STONE;
       
      // You can, for example, print custom names for certain materials
      //if (item.getType() == stone)
      //  return "My Shiny Little Stone";
    
      // We use a class that is packed in Spigot server's JAR to capitalize our item
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
      var wrapme = wordUtils.capitalize(name);
      // Return the item name deducted from item's type, capitalized
      return "[" + wrapme + "]";
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

# What texts should be displayed when we hover the mouse
# over this variable in the chat
Hover: []

# What ItemStack should be displayed when we hover the mouse over this variable in the chat
Hover_Item: player.getItemInHand()

# What website URL should be opened when we click with the mouse
# on this variable in the chat
Open_Url: ''

# What command should appear in the player command box on his screen
# if he clicks on this variable in the chat
Suggest_Command: ''

# What command should run as the sender when he clicks the mouse on this variable?
# Minecraft only supports 1 command!
Run_Command: ''
```

If you're on a local test server, you may need to restart the server for the changes to work.

**Comment by ElBananaa** [comment] 2021-12-23 02:07
Closing this for now, as it worked fine on my side, let me know down below if your issue persists ;)

**Closed as completed by ElBananaa** 2021-12-23 02:07 UTC

**Comment by kangarko** [comment] 2021-12-23 08:22
There's a second case needing replacement in metadata.getDisplayName that Banana missed, this cleaned version will work 100%:

```yaml
# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: message

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
Key: item

# The value the key will be replaced to. This uses JavaScript.
Value: |-
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      
      if (item == null || item.getType().toString().contains("AIR")) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      if (metadata != null && metadata.hasDisplayName())
        return "\[" + metadata.getDisplayName() + "\]";
      
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
    
      return "\[" + wordUtils.capitalize(name) + "\]";
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

# What texts should be displayed when we hover the mouse
# over this variable in the chat
Hover: []

# What ItemStack should be displayed when we hover the mouse over this variable in the chat
Hover_Item: player.getItemInHand()

# What website URL should be opened when we click with the mouse
# on this variable in the chat
Open_Url: ''

# What command should appear in the player command box on his screen
# if he clicks on this variable in the chat
Suggest_Command: ''

# What command should run as the sender when he clicks the mouse on this variable?
# Minecraft only supports 1 command!
Run_Command: ''
```

Result:


<img width="472" alt="Screenshot 2021-12-23 at 09 21 56" src="https://user-images.githubusercontent.com/1918426/147210783-5e05e1a2-67d2-4bb9-8d99-4e691844566e.png">

**Comment by TomLewis** [comment] 2021-12-23 17:11
Is this reliant on a reboot?
```
[17:10:14] [Async Chat Thread - #11/INFO]: [ChatControlRed] ChatControlRed 10.8.6 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
[17:10:14] [Async Chat Thread - #11/INFO]: java.lang.RuntimeException: Found invalid or unparsed variable in 'MemorySection[path='Parts.discord.Sender_Condition', root='SimpleYaml']'
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:201)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:118)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:239)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:209)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:510)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:178)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[17:10:14] [Async Chat Thread - #11/INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[17:10:14] [Async Chat Thread - #11/INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:10:14] [Async Chat Thread - #11/INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[17:10:14] [Async Chat Thread - #11/INFO]: at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230)
[17:10:14] [Async Chat Thread - #11/INFO]: at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115)
[17:10:14] [Async Chat Thread - #11/INFO]: at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.lang.Thread.run(Thread.java:833)
[17:10:14] [Async Chat Thread - #11/INFO]: <eval>:1 ReferenceError: "MemorySection" is not defined
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:169)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:118)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:239)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:209)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:510)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:178)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32)
[17:10:14] [Async Chat Thread - #11/INFO]: at ChatControl-Red-10.8.6.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[17:10:14] [Async Chat Thread - #11/INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[17:10:14] [Async Chat Thread - #11/INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:10:14] [Async Chat Thread - #11/INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[17:10:14] [Async Chat Thread - #11/INFO]: at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230)
[17:10:14] [Async Chat Thread - #11/INFO]: at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115)
[17:10:14] [Async Chat Thread - #11/INFO]: at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:10:14] [Async Chat Thread - #11/INFO]: at java.base/java.lang.Thread.run(Thread.java:833)
[17:10:14] [Async Chat Thread - #11/INFO]: [ChatControlRed] !-----------------------------------------------------!
[17:10:14] [Async Chat Thread - #11/INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
[17:10:14] [Async Chat Thread - #11/INFO]: [ChatControlRed] !-----------------------------------------------------!
```

At some point it seemed to work, but I think I must have rebooted.
Trying that just gives me this error.

**Comment by TomLewis** [comment] 2021-12-23 17:20
Nearly working.

I wanted to colorize the brackets with ` return "\&8[&r" + wordUtils.capitalize(name) + "\&8]";` but for some reason that last bracket is not being reset to &8 if you use a colored item in [item]
![2021-12-23_17 19 03](https://user-images.githubusercontent.com/144046/147273144-3b6e2b73-88b4-47f9-8f7d-d05003cd76e6.png)

So empty/blank items are being shown with the correct color, when you use an item with color in it, it somehow completely ignores the color added to the second bracket.

Also stairs are not considered items and it triggers a message for empty hand.

**Comment by ElBananaa** [comment] 2021-12-23 17:36
You also need to change brackets colors everywhere for this to work:
```js
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      
      if (item == null || item.getType().toString().contains("AIR")) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      if (metadata != null && metadata.hasDisplayName())
        return "\&8[" + metadata.getDisplayName() + "\&8]";
      
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
    
      return "\&8[" + wordUtils.capitalize(name) + "\&8]";
    }
```

As for the stairs, I'm unable to reproduce your issue (even with 1.18 stairs).
Are you using the latest version of the plugin? It only happens with specific stairs?

**Comment by TomLewis** [comment] 2021-12-23 17:42
Brilliant that worked thank you.
Now for items that don't work, like stairs?

**Comment by ElBananaa** [comment] 2021-12-23 17:44
> Brilliant that worked thank you. Now for items that don't work, like stairs?

As I said above:
>As for the stairs, I'm unable to reproduce your issue (even with 1.18 stairs).
Are you using the latest version of the plugin? It only happens with specific stairs?

**Comment by TomLewis** [comment] 2022-01-02 18:30
No stairs work.

**Comment by ElBananaa** [comment] 2022-01-02 18:39
Seems like a weird issue. I'm absolutely unable to reproduce your issue, no matter the setup (I tried on my two production servers, my local test server, and another test server located on a VPS.
My guess is that either one of your plugin, or one of you config is causing the issue. (If you're using a custom server software, this may also be the cause of the issue)

**Comment by TomLewis** [comment] 2022-01-02 21:26
> Seems like a weird issue. I'm absolutely unable to reproduce your issue, no matter the setup (I tried on my two production servers, my local test server, and another test server located on a VPS. My guess is that either one of your plugin, or one of you config is causing the issue. (If you're using a custom server software, this may also be the cause of the issue)

PurPur 1.17.1
Only changes are those brackets around the item.

**Comment by kangarko** [comment] 2022-01-03 16:15
Can you give me an screenshot of the stairs not working? Whats the exact words?

**Comment by TomLewis** [comment] 2022-01-03 16:59
It thinks you have an empty hand.
![2022-01-03_16 59 09](https://user-images.githubusercontent.com/144046/147958084-24db3802-2dcf-4f37-8646-c2a819f902b0.png)

**Comment by kangarko** [comment] 2022-01-03 17:35
Any console error?

**Comment by TomLewis** [comment] 2022-01-03 18:20
Nope, nothing.

**Comment by kangarko** [comment] 2022-01-04 16:09
Oh shit. AIR is contained in st**AIR**s. Probably a lot more false catches. Will patch the item.yml file internally too. Use this code:

See that is uses either "equals" or contains with _ in front. Minecraft 1.13 has AIR, CAVE_AIR and VOID_AIR so complicated unfortunately.

```yaml
# The value the key will be replaced to. This uses JavaScript.
Value: |-
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      var itemMaterial = item.getType().toString();
      
      if (item == null || itemMaterial.equals("AIR") || itemMaterial.contains("_AIR")) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      if (metadata != null && metadata.hasDisplayName())
        return "\&8[&d" + metadata.getDisplayName() + "\&8]";
      
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
    
      return "\&8[&d" + wordUtils.capitalize(name) + "\&8]";
    }
```

**Comment by TomLewis** [comment] 2022-01-06 13:52
Ha! That's a funny one.
I typed "Air" into https://minecraftitemids.com/ and it does look like its just stairs somehow! 

I will try out this adapted code.

**Comment by TomLewis** [comment] 2022-01-06 21:14
I found another bug @kangarko 

Items without enchants do not have hover over effects, we have a TON of items with custom lore in them, thousands and thousands, but we cant show these in chat as a lot do not have enchants on them.

**Comment by kangarko** [comment] 2022-01-12 10:59
Sorry, cannot reproduce. I only placed a custom lore on the item: https://i.imgur.com/WcjvN1D.png and it just works: https://i.imgur.com/vVdx5nU.png

Using 1.18 thought, you're still on 1.17 or? Looks like a Minecraft itemstack to JSON encoding issue to me.

**Comment by kangarko** [comment] 2022-01-12 11:03
Try doing /chc info item yourName while holding that item and let me know the console output in the next version.
