### ISSUE TITLE
1.21: Items Adder placeholder not working 

### ISSUE THREAD

**Issue by LixaSl** [kangarko/ChatControl#2866] opened 2024-11-15 10:02 UTC
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.2

### Steps to reproduce

items adder placeholder not working (Before updating the plugin everything worked, but it doesn’t work in this one)

![image](https://github.com/user-attachments/assets/81c32783-1485-4a40-b441-1dcc9b16926c)

**Comment by kangarko** [comment] 2024-11-15 18:15
I can't reproduce on the latest 1.21.1:

![a](https://i.imgur.com/IfExN0i.png)

Can you tell me where did you configure these placeholders and send me your /chc debug?

PS: We only support itemsadder 4

**Comment by LixaSl** [comment] 2024-11-15 18:38
> I can't reproduce on the latest 1.21.1:
> 
> ![a](https://camo.githubusercontent.com/09890edddcb9584d3ef805f15e7dabcf8ff09d770255a247bf60b47ddc57f95d/68747470733a2f2f692e696d6775722e636f6d2f496645784e30692e706e67)
> 
> Can you tell me where did you configure these placeholders and send me your /chc debug?
> 
> PS: We only support itemsadder 4

yes, everything works through colons anyway, but the placeholder in percentages is not there, the same prefix above the head is in the %% format, and they are displayed in all plugins except this one (on an older version of the plugin, on version 1.19.2, everything worked fine)
![image](https://github.com/user-attachments/assets/0bc174ae-8245-46b2-9ff1-e47863bfc814)

debug link: https://ufile.io/s69f1b9b

Ps: One of the users on discord also has a broken %img....% in the screenshot.
![image](https://github.com/user-attachments/assets/a161d222-b3e5-44c2-9c83-2976e358e77b)

**Comment by kangarko** [comment] 2024-11-18 17:56
Can you replace the %% syntax with {} instead?

**Comment by kangarko** [comment] 2024-11-24 15:05
Closing due to inacitivity, comment below when you come back

**Closed as completed by kangarko** 2024-11-24 15:05 UTC

**Comment by LixaSl** [comment] 2024-12-02 15:46
> Closing due to inacitivity, comment below when you come back

![image](https://github.com/user-attachments/assets/78c79b8c-e766-48b2-8e50-5659353b6639)

**Comment by LixaSl** [comment] 2024-12-02 15:47
> Closing due to inacitivity, comment below when you come back

![image](https://github.com/user-attachments/assets/3ee5762e-d0eb-42bd-964b-94ee7f18adcc)
and the same tab does not support this format, so it is clearly the plugin's fault (well, on the old version like 1.20.1 everything worked fine, as soon as I updated the server and this plugin stopped)

lp editor prefix: %img_offset_-10%%img_owner%
chat config:   prefix:
    Message: '&c✧&f&r {player_prefix}'
- that is, the placeholder is taken from Luckperms itself, and the picture is NOT displayed, although it is displayed in all other plugins (I repeat that everything works on the old version)

**Comment by LixaSl** [comment] 2024-12-02 16:22
![image](https://github.com/user-attachments/assets/687cd26b-1465-4ed6-8005-25956de2aa3a)
*screen 1.20.1*
ChatControl on version 10.23.5 works properly

**Comment by LixaSl** [comment] 2024-12-04 11:15
> Closing due to inacitivity, comment below when you come back

as a fact, the prefix for sending via discord appears correctly, but does not work in chats, you should definitely fix these placeholders
![image](https://github.com/user-attachments/assets/5b988b8c-beb6-455b-b3fd-0e74206dfa0b)

**Comment by kangarko** [comment] 2024-12-04 13:10
You can stay on 10.23.5 and re-test on v11 once it's out please, I will make sure it is working again there.

**Comment by LixaSl** [comment] 2024-12-04 13:18
> You can stay on 10.23.5 and re-test on v11 once it's out please, I will make sure it is working again there.

it won't start on version 1.21
then I will wait for the new 11th version, good luck to you

**Comment by kangarko** [comment] 2024-12-04 13:38
What is the issue on 10.23.5 and 1.21?

**Comment by LixaSl** [comment] 2024-12-04 14:35
> What is the issue on 10.23.5 and 1.21?

![image](https://github.com/user-attachments/assets/ccad788a-977a-4a24-9505-22184bd5d695)
starting from 27th it doesn't start

**Comment by kangarko** [comment] 2024-12-04 14:49
Gotcha, because itemsadder has updated, so you would need to stay on its old version too, if that is incompatible then please wait for v11

**Comment by LixaSl** [comment] 2024-12-04 14:50
> Gotcha, because itemsadder has updated, so you would need to stay on its old version too, if that is incompatible then please wait for v11

I will wait, thank you for paying attention to the problem
