### ISSUE TITLE
1.18.2: Clickable links in chat not working

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#1906] opened 2022-05-25 00:40 UTC
Minecraft Version: 118.2
MySQL: true
BungeeCord: false

Updating to the latest version of chat control only allows some users to click certain links and not others. Debug file found in Email to support@mineacademy.org with same title as this issue.

**Comment by ElBananaa** [comment] 2022-05-25 03:07
Dupe of #1905, let's continue there.

**Closed as completed by ElBananaa** 2022-05-25 03:07 UTC
